'use strict'

const fs = require('fs')
const path = require('path')
const os = require('os')

const GOV_DIRS = [
  'docs/adr',
  'docs/req',
  'docs/roadmaps/backlog',
  'docs/roadmaps/analyzing',
  'docs/roadmaps/wip',
  'docs/roadmaps/blocked',
  'docs/roadmaps/done',
  'docs/roadmaps/abandoned',
]

/**
 * scaffold(cfg) — cria diretórios de governança e gera arquivos de configuração.
 * cfg = { projectName, projectType, frontend, backend, pkgManager, hooks, ci }
 */
async function scaffold(cfg) {
  for (const dir of GOV_DIRS) {
    fs.mkdirSync(dir, { recursive: true })
    console.log(`  ✓ ${dir}`)
  }

  writeTrackfwConfig(cfg)
  generateValidateScript(cfg)
  generateAttentionScripts(cfg)
  generateCIWorkflow(cfg)
  generateGitHooks(cfg)
  generateCommitMsgHook(cfg)
  generateClaudeMD(cfg)
  if (cfg.backend === 'java') generatePomXml(cfg)
  generateClaudeCommands()
}

// ---------------------------------------------------------------------------
// trackfw.yaml
// ---------------------------------------------------------------------------

function writeTrackfwConfig(cfg) {
  const today = new Date().toISOString().slice(0, 10)
  let content = `# trackfw configuration
# generated: ${today}

frontend: ${cfg.frontend || ''}
backend: ${cfg.backend || ''}
backend_framework: ${cfg.backendFramework || ''}
pkg_manager: ${cfg.pkgManager || ''}
hooks: ${cfg.hooks || ''}
ci: ${cfg.ci || ''}
require_req_in_commit: ${cfg.requireReqInCommit ? 'true' : 'false'}

# governance paths (edit to match your project structure)
adr_dirs:
  - docs/adr
req_dir: docs/req
roadmap_dir: docs/roadmaps
roadmap_namespacing: flat
`
  if (cfg.brownfieldMode) {
    const until = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10)
    content += `governance_mode: lenient\nlenient_until: ${until}\n`
  }
  fs.writeFileSync('trackfw.yaml', content, 'utf8')
  console.log('  ✓ trackfw.yaml')
}

// ---------------------------------------------------------------------------
// scripts/trackfw-validate.sh
// ---------------------------------------------------------------------------

function generateValidateScript(cfg) {
  fs.mkdirSync('scripts', { recursive: true })

  const script = buildValidateScript(cfg)
  const scriptPath = path.join('scripts', 'trackfw-validate.sh')
  fs.writeFileSync(scriptPath, script, { encoding: 'utf8', mode: 0o755 })
  console.log(`  ✓ ${scriptPath}`)
}

function buildValidateScript(cfg) {
  let base = `#!/usr/bin/env sh
# trackfw governance gate — generated by trackfw init
set -e

echo "→ trackfw: validating governance..."
trackfw validate

`

  switch (cfg.backend) {
    case 'go':
      base += 'echo "→ build check (go)..."\ngo build ./...\n'
      break
    case 'java':
      base += 'echo "→ build check (maven)..."\nmvn compile -q\n'
      break
    case 'node': {
      const pm = cfg.pkgManager || 'npm'
      base += `echo "→ build check (node)..."\n${pm} run build\n`
      break
    }
    case 'python':
      base += "echo \"→ build check (python)...\"\npython3 -c \"import pathlib, py_compile; [py_compile.compile(str(p), doraise=True) for p in pathlib.Path('.').rglob('*.py') if '.venv' not in p.parts and 'venv' not in p.parts]\"\n"
      break
  }

  if (['react', 'vue', 'angular'].includes(cfg.frontend)) {
    const pm = cfg.pkgManager && cfg.pkgManager !== 'none' ? cfg.pkgManager : 'npm'
    base += `echo "→ frontend build check..."\n${pm} run build\n`
  }

  base += '\necho "✓ all checks passed."\n'
  return base
}

// ---------------------------------------------------------------------------
// scripts/trackfw-attention-signal.sh + trackfw-attention-cleanup.sh
// ---------------------------------------------------------------------------

function generateAttentionScripts(cfg, cwd) {
  const { generateAttentionScripts: gen } = require('./hooks')
  gen(cfg, cwd || process.cwd())
}

// ---------------------------------------------------------------------------
// CI workflows
// ---------------------------------------------------------------------------

function generateCIWorkflow(cfg) {
  switch (cfg.ci) {
    case 'github-actions':
      generateGitHubActionsWorkflow()
      break
    case 'gitlab-ci':
      generateGitLabCIWorkflow()
      break
  }
}

function generateGitHubActionsWorkflow() {
  fs.mkdirSync('.github/workflows', { recursive: true })

  const content = `name: trackfw-gate
on:
  pull_request:
    branches: [main]

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install trackfw
        run: |
          curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh

      - name: Governance gate
        run: trackfw validate
`

  const filePath = '.github/workflows/trackfw-gate.yml'
  fs.writeFileSync(filePath, content, 'utf8')
  console.log(`  ✓ ${filePath}`)
}

function generateGitLabCIWorkflow() {
  const content = `# trackfw governance gate
trackfw-gate:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
    - curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh
  script:
    - trackfw validate
  only:
    - merge_requests
`

  fs.writeFileSync('.gitlab-ci-trackfw.yml', content, 'utf8')
  console.log('  ✓ .gitlab-ci-trackfw.yml')
}

// ---------------------------------------------------------------------------
// Git hooks
// ---------------------------------------------------------------------------

function generateGitHooks(cfg) {
  switch (cfg.hooks) {
    case 'husky':
      generateHuskyHook()
      break
    case 'lefthook':
      generateLefthookHook()
      break
  }
}

function generateHuskyHook() {
  fs.mkdirSync('.husky', { recursive: true })
  const content = '#!/usr/bin/env sh\n. "$(dirname -- "$0")/_/husky.sh"\n\ntrackfw validate\n'
  const filePath = '.husky/pre-commit'
  fs.writeFileSync(filePath, content, { encoding: 'utf8', mode: 0o755 })
  console.log(`  ✓ ${filePath}`)
}

function generateLefthookHook() {
  const content = `pre-commit:
  commands:
    trackfw-validate:
      run: trackfw validate
`
  fs.writeFileSync('lefthook.yml', content, 'utf8')
  console.log('  ✓ lefthook.yml')
}

function generateCommitMsgHook(cfg) {
  if (!cfg.requireReqInCommit || cfg.hooks === 'none') return

  const script = [
    '#!/bin/sh',
    '# trackfw: require REQ reference in feat/* and fix/* branches',
    'BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")',
    'case "$BRANCH" in',
    '  feat/*|fix/*)',
    '    if ! grep -qE "^(REQ|req): " "$1"; then',
    '      echo "ERROR: Commits in feat/* and fix/* branches require a REQ reference."',
    '      echo "  Add to commit body: REQ: REQ-YYYY-MM-DD-your-req-slug"',
    '      exit 1',
    '    fi',
    '    ;;',
    'esac',
    '',
  ].join('\n')

  if (cfg.hooks === 'husky') {
    fs.mkdirSync('.husky', { recursive: true })
    fs.writeFileSync('.husky/commit-msg', script, { encoding: 'utf8', mode: 0o755 })
    console.log('  ✓ .husky/commit-msg')
  } else if (cfg.hooks === 'lefthook') {
    const lefthookPath = 'lefthook.yml'
    const existing = fs.existsSync(lefthookPath) ? fs.readFileSync(lefthookPath, 'utf8') : ''
    if (!existing.includes('commit-msg:')) {
      const addition = '\ncommit-msg:\n  scripts:\n    "trackfw-req-check.sh":\n      runner: sh\n'
      fs.writeFileSync(lefthookPath, existing + addition, 'utf8')
    }
    fs.mkdirSync('.lefthook/commit-msg', { recursive: true })
    fs.writeFileSync('.lefthook/commit-msg/trackfw-req-check.sh', script, { encoding: 'utf8', mode: 0o755 })
    console.log('  ✓ .lefthook/commit-msg/trackfw-req-check.sh')
  }
}

// ---------------------------------------------------------------------------
// pom.xml (Java / Spring Boot)
// ---------------------------------------------------------------------------

function generatePomXml(cfg) {
  const slug = cfg.projectName
    ? cfg.projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '')
    : 'my-app'
  const name = cfg.projectName || 'My App'
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.0</version>
    <relativePath/>
  </parent>
  <groupId>com.example</groupId>
  <artifactId>${slug}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>${name}</name>
  <description>${name} — generated by trackfw</description>
  <properties>
    <java.version>21</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
`
  fs.writeFileSync('pom.xml', content, 'utf8')
  console.log('  ✓ pom.xml')
}

// ---------------------------------------------------------------------------
// trackfw rules inject-or-update (idempotente via marcadores HTML)
// ---------------------------------------------------------------------------

const RULES_START = '<!-- trackfw:rules:start -->'
const RULES_END = '<!-- trackfw:rules:end -->'

const AGENT_FILES = {
  claude:   'CLAUDE.md',
  codex:    'AGENTS.md',
  gemini:   'GEMINI.md',
  copilot:  '.github/copilot-instructions.md',
  windsurf: '.windsurfrules',
  amazonq:  '.amazonq/developer/guidelines.md',
  cursor:   '.cursor/rules/trackfw.mdc',
}

const AGENT_HEADERS = {
  claude:   '# Project Instructions\n',
  codex:    '# Project Instructions\n',
  gemini:   '# Project Instructions\n',
  copilot:  '# GitHub Copilot Instructions\n',
  windsurf: '# Windsurf Rules\n',
  amazonq:  '# Amazon Q Developer Guidelines\n',
  cursor:   '---\ndescription: trackfw governance rules\nglob: "**/*"\nalwaysApply: true\n---\n',
}

function trackfwRulesBlock() {
  return RULES_START + `
## trackfw — Governance Rules

This project uses **trackfw** for AI-native delivery governance.
Chain: \`ADR → REQ → ROADMAP\` · States: \`backlog / analyzing / wip / blocked / done / abandoned\`

### Agent Protocol
1. **Before starting:** run \`trackfw context\` · read \`docs/agents-working-context.md\`
2. **After finishing:** update \`docs/agents-working-context.md\` with what changed
3. **Before PR:** \`trackfw validate\` must pass
4. **ML lifecycle — mandatory:**
   - Starting a ML: edit roadmap \`**Status:** ⬜ Pendente\` → \`**Status:** 🔄 Em andamento\` + commit.
   - Completing a ML: edit roadmap → \`**Status:** ✅ Concluído\` + include in ML commit.
   - Analyzing a roadmap: move from \`backlog/\` to \`analyzing/\`; to \`wip/\` only when coding starts.

### Attention Signal (when you need user input during a task)
Write \`docs/roadmaps/.trackfw-attention.json\`:
\`\`\`json
{"roadmap":"file.md","ml":"ML-1A","message":"what you need","level":"action_required","timestamp":"ISO8601Z"}
\`\`\`
Delete the file when resolved. Visible as a live banner in \`trackfw serve\`.
` +
'\n### Architecture Directives (mandatory)\n' +
'- **3-layer arch + no in-memory data:** frontend / backend / database; always DB + ORM — never arrays/globals\n' +
'- **Auth + Docker + .env from day 1:** never defer auth; containerize early; all config via env vars\n' +
'- **2-layer validation + API-first:** frontend (UX) + backend (security); define OpenAPI contract first\n' +
'- **Security wave + test coverage:** red-team review in every roadmap; TDD for critical; min 60%/80%\n' +
'- Use `/trackfw:architect` to define stack before the first REQ\n' +
RULES_END
}

/**
 * injectOrUpdateRules — injeta ou atualiza o bloco de regras trackfw no arquivo.
 * - Arquivo não existe: cria com headerIfNew + bloco de regras
 * - Arquivo existe, sem marcador: appenda o bloco no final
 * - Arquivo existe, com marcador: substitui conteúdo entre marcadores
 */
function injectOrUpdateRules(filePath, headerIfNew) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })

  const block = trackfwRulesBlock()

  if (!fs.existsSync(filePath)) {
    let content = headerIfNew || ''
    if (content && !content.endsWith('\n')) content += '\n'
    content += '\n' + block + '\n'
    fs.writeFileSync(filePath, content, 'utf8')
    return
  }

  let content = fs.readFileSync(filePath, 'utf8')

  const start = content.indexOf(RULES_START)
  if (start === -1) {
    // No marker: append
    if (!content.endsWith('\n')) content += '\n'
    content += '\n' + block + '\n'
    fs.writeFileSync(filePath, content, 'utf8')
    return
  }

  // Has marker: replace between start and end
  const end = content.indexOf(RULES_END, start)
  if (end === -1) {
    // Malformed: append new block
    content += '\n' + block + '\n'
    fs.writeFileSync(filePath, content, 'utf8')
    return
  }

  const newContent = content.slice(0, start) + block + content.slice(end + RULES_END.length)
  fs.writeFileSync(filePath, newContent, 'utf8')
}

/**
 * injectRulesForTool — injeta regras trackfw no arquivo de config do tool dado.
 * tool: 'claude' | 'codex' | 'gemini' | 'copilot' | 'windsurf' | 'amazonq' | 'cursor'
 * cwd: diretório raiz do projeto (default: process.cwd())
 */
function injectRulesForTool(tool, cwd) {
  const relPath = AGENT_FILES[tool]
  if (!relPath) return
  const header = AGENT_HEADERS[tool] || ''
  injectOrUpdateRules(path.join(cwd || process.cwd(), relPath), header)
}

/**
 * injectRulesDetected — varre cwd por arquivos de config de agentes existentes
 * e injeta as regras trackfw em cada um encontrado.
 * Cursor: injeta também se .cursor/ existir, mesmo que trackfw.mdc não exista ainda.
 */
function injectRulesDetected(cwd) {
  const root = cwd || process.cwd()
  for (const [tool, relPath] of Object.entries(AGENT_FILES)) {
    if (tool === 'cursor') {
      if (fs.existsSync(path.join(root, '.cursor'))) {
        try { injectRulesForTool('cursor', root) } catch (_) {}
      }
      continue
    }
    if (fs.existsSync(path.join(root, relPath))) {
      try { injectRulesForTool(tool, root) } catch (_) {}
    }
  }
}

// ---------------------------------------------------------------------------
// CLAUDE.md
// ---------------------------------------------------------------------------

function generateClaudeMD(cfg) {
  const today = new Date().toISOString().slice(0, 10)
  const projectName = cfg.projectName || 'my-project'

  let content = `# ${projectName} — Claude Code Instructions\n\n`
  content += `> Generated by trackfw on ${today}. Update this file as the project evolves.\n\n`

  content += '## Project overview\n\n'
  content += '<!-- Describe what this project does in 2-3 sentences. -->\n\n'

  content += '## Governance chain\n\n'
  content += '```\nADR → REQ → ROADMAP → backlog / analyzing / wip / blocked / done / abandoned\n```\n\n'

  content += '## Agent rules (mandatory)\n\n'
  content += 'These rules apply to every agent or AI assistant working in this project:\n\n'
  content += '1. **Never start coding without a REQ and a ROADMAP.** If none exists, create them first.\n'
  content += '2. **Use `/trackfw:implement <req-slug>` to start any implementation.** This skill orchestrates the full flow automatically: finds or generates the roadmap, moves it to `wip/`, executes each ML, updates the roadmap, and moves to `done/`.\n'
  content += '3. **Only one roadmap in `wip/` at a time.** Before starting a new one, complete or move to `blocked/` the current one.\n'
  content += '4. **Ciclo de vida do ML — obrigatório:**\n'
  content += '   - Ao **iniciar** um ML: edite o roadmap alterando `**Status:** ⬜ Pendente` → `**Status:** 🔄 Em andamento` e faça commit do roadmap.\n'
  content += '   - Ao **concluir** um ML: edite o roadmap alterando `**Status:** 🔄 Em andamento` → `**Status:** ✅ Concluído` e inclua essa mudança no commit do ML.\n'
  content += '   - Ao **analisar** um roadmap antes de iniciar: mova o arquivo de `backlog/` para `analyzing/`; só mova para `wip/` ao começar a codificar de fato.\n'
  content += '5. **Run `trackfw validate` before every commit.** Zero violations required.\n'
  content += '6. **ADRs before decisions.** Any architectural or technical decision must have an ADR (`/trackfw:adr`).\n\n'

  content += '## Slash commands (Claude Code)\n\n'
  content += '| Command | When to use |\n'
  content += '|---|---|\n'
  content += '| `/trackfw:implement <req>` | **Start here** — orchestrates full implementation flow |\n'
  content += '| `/trackfw:adr <title>` | Before any architectural decision |\n'
  content += '| `/trackfw:req <title>` | Before any implementation work |\n'
  content += '| `/trackfw:roadmap <req>` | Generate AI roadmap from a REQ |\n'
  content += '| `/trackfw:move <name> <state>` | Move roadmap between states manually |\n'
  content += '| `/trackfw:validate` | Run governance validation |\n'
  content += '| `/trackfw:status` | Check what is in flight |\n\n'

  content += '## CLI commands (terminal / CI)\n\n'
  content += '| Command | When to use |\n'
  content += '|---|---|\n'
  content += '| `trackfw adr new "title"` | Create ADR |\n'
  content += '| `trackfw req new "title"` | Create REQ |\n'
  content += '| `trackfw roadmap new` | Create empty roadmap linked to a REQ |\n'
  content += '| `trackfw roadmap move <name> <state>` | Move roadmap state |\n'
  content += '| `trackfw validate` | Governance validation gate |\n'
  content += '| `trackfw status` | Show governance status |\n\n'

  // Frontend section
  if (cfg.frontend && cfg.frontend !== 'none' && cfg.frontend !== '') {
    const pm = (cfg.pkgManager && cfg.pkgManager !== 'none') ? cfg.pkgManager : 'npm'
    content += '## Frontend\n\n'
    content += `Stack: ${cfg.frontend}\n`
    content += `Package manager: ${pm}\n\n`
    content += 'Build commands:\n'
    content += `  ${pm} run build     # build\n`
    content += `  ${pm} run dev       # dev server\n`
    content += `  ${pm} run test      # tests\n\n`
    content += 'Rules:\n'
    content += `- Build must pass (\`${pm} run build\`) before marking any ML as done\n`
    content += '- Run `trackfw validate` before committing frontend changes\n\n'
  }

  // Backend section
  if (cfg.backend && cfg.backend !== 'none' && cfg.backend !== '') {
    const [buildCmd, testCmd, lintCmd] = backendCommands(cfg)
    content += '## Backend\n\n'
    content += `Stack: ${cfg.backend}\n\n`
    content += 'Build commands:\n'
    content += `  ${buildCmd}   # build / compile check\n`
    content += `  ${testCmd}   # tests\n`
    content += `  ${lintCmd}   # lint / vet\n\n`
    content += 'Rules:\n'
    content += '- Build must pass before marking any ML as done\n'
    content += '- Run `trackfw validate` before committing backend changes\n\n'
  }

  // Pre-commit checklist
  content += '## Pre-commit checklist\n\n'
  content += 'Before every commit:\n'
  content += '- [ ] `trackfw validate` passes with zero violations\n'
  if (cfg.backend && cfg.backend !== 'none' && cfg.backend !== '') {
    const [buildCmd] = backendCommands(cfg)
    content += `- [ ] \`${buildCmd}\` passes\n`
  }
  if (cfg.frontend && cfg.frontend !== 'none' && cfg.frontend !== '') {
    const pm = (cfg.pkgManager && cfg.pkgManager !== 'none') ? cfg.pkgManager : 'npm'
    content += `- [ ] \`${pm} run build\` passes\n`
  }
  content += '\n'

  // Git hooks section
  content += '## Git hooks\n\n'
  switch (cfg.hooks) {
    case 'husky':
      content += 'Git hook configured in `.husky/pre-commit` — runs `trackfw validate` automatically.\n\n'
      break
    case 'lefthook':
      content += 'Git hook configured in `lefthook.yml` — runs `trackfw validate` automatically.\n\n'
      break
    default:
      content += 'No git hook configured. Run `trackfw validate` manually before every commit.\n\n'
  }

  // CI gate section
  content += '## CI gate\n\n'
  switch (cfg.ci) {
    case 'github-actions':
      content += '`.github/workflows/trackfw-gate.yml` runs `trackfw validate` on every pull request to main.\n'
      break
    case 'gitlab-ci':
      content += '`.gitlab-ci-trackfw.yml` runs `trackfw validate` on every merge request.\n'
      break
    default:
      content += 'No CI gate configured.\n'
  }

  injectOrUpdateRules('CLAUDE.md', content)
  console.log('  ✓ CLAUDE.md')
}

/**
 * Retorna [buildCmd, testCmd, lintCmd] para o backend configurado.
 */
function backendCommands(cfg) {
  const pm = (cfg.pkgManager && cfg.pkgManager !== 'none') ? cfg.pkgManager : 'npm'
  switch (cfg.backend) {
    case 'go':
      return ['go build ./...', 'go test ./...', 'go vet ./...']
    case 'java':
      return ['mvn package -q', 'mvn test', 'mvn compile -q']
    case 'node':
      return [`${pm} run build`, `${pm} test`, `${pm} run lint`]
    case 'python':
      return [
        "python3 -c \"import pathlib, py_compile; [py_compile.compile(str(p), doraise=True) for p in pathlib.Path('.').rglob('*.py') if '.venv' not in p.parts and 'venv' not in p.parts]\"",
        'python -m pytest',
        'ruff check .',
      ]
    default:
      return ['', '', '']
  }
}

// ---------------------------------------------------------------------------
// .claude/commands/trackfw/ — 7 slash commands
// ---------------------------------------------------------------------------

function generateClaudeCommands() {
  const dir = '.claude/commands/trackfw'
  fs.mkdirSync(dir, { recursive: true })

  const commands = {
    'adr.md': `Execute o seguinte comando bash: \`trackfw adr new "$ARGUMENTS"\`

Se o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:

\`\`\`
trackfw não está instalado. Instale com uma das opções:

  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh
  npm install -g trackfw
  pip install trackfw
\`\`\``,

    'req.md': `Execute o seguinte comando bash: \`trackfw req new "$ARGUMENTS"\`

Se o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:

\`\`\`
trackfw não está instalado. Instale com uma das opções:

  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh
  npm install -g trackfw
  pip install trackfw
\`\`\``,

    'validate.md': `Execute o seguinte comando bash: \`trackfw validate\`

Se o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:

\`\`\`
trackfw não está instalado. Instale com uma das opções:

  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh
  npm install -g trackfw
  pip install trackfw
\`\`\``,

    'status.md': `Execute o seguinte comando bash: \`trackfw status\`

Se o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:

\`\`\`
trackfw não está instalado. Instale com uma das opções:

  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh
  npm install -g trackfw
  pip install trackfw
\`\`\``,

    'move.md': `Execute o seguinte comando bash: \`trackfw roadmap move $ARGUMENTS\`

O formato esperado é: \`<nome-do-roadmap> <estado>\`

Estados válidos: \`backlog\`, \`analyzing\`, \`wip\`, \`blocked\`, \`done\`, \`abandoned\`

Exemplo: \`/trackfw:move meu-roadmap analyzing\`

Se o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:
trackfw não está instalado. Instale com:
  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh
  npm install -g trackfw
  pip install trackfw`,

    'roadmap.md': `Gere um roadmap de implementação em microlotes para uma REQ do projeto.

## Passos

1. **Listar REQs disponíveis**
   Use Glob para listar \`docs/req/*.md\`. Se nenhum arquivo encontrado, informe:
   > Nenhuma REQ encontrada em \`docs/req/\`. Crie uma primeiro com \`/trackfw:req\`.

2. **Selecionar a REQ**
   - Se \`$ARGUMENTS\` foi fornecido: use como filtro (substring case-insensitive) para encontrar o arquivo
   - Se não foi fornecido ou o filtro não encontrar exatamente um: liste os arquivos disponíveis e pergunte ao usuário qual usar
   - Leia o conteúdo completo do arquivo REQ selecionado

3. **Gerar o roadmap**
   Com base no conteúdo da REQ, gere um roadmap seguindo **estritamente** este formato:

   \`\`\`markdown
   # Roadmap: <título derivado da REQ>

   > Criado em: <YYYY-MM-DD> | Status: ⬜ Backlog

   ## Diagnóstico / Contexto
   <resumo do problema, motivação e escopo extraídos da REQ>

   ## Wave 1 — <nome descritivo> (<N> MLs em paralelo)
   > Dependências: Independente

   ### ML-1A — <título>
   **Status:** ⬜ Pendente
   **Arquivos afetados:**
   - \`caminho/exato/do/arquivo\`
   **Ações:**
   - Descrição detalhada da ação com valores, chaves e comandos exatos
   **Critérios de aceite:**
   - [ ] build sem erros
   - [ ] testes verdes
   **Comandos de validação:** \`<comando de build e teste do projeto>\`
   \`\`\`

   **Princípios obrigatórios:**
   - MLs dentro da mesma Wave são **independentes** (arquivos distintos, sem conflito)
   - Cada ML deve ser detalhado o suficiente para execução por um agente sem contexto extra
   - Maximizar paralelismo: agrupe em paralelo tudo que não compartilhar arquivos
   - Waves sequenciais apenas quando há dependência real de resultado
   - Critérios de aceite mensuráveis em cada ML

4. **Salvar o arquivo**
   - Calcule o slug: título em lowercase, espaços → hifens, remova caracteres especiais
   - Crie o arquivo em \`docs/roadmaps/backlog/ROADMAP-<YYYY-MM-DD>-<slug>.md\`
   - Use a data de hoje

5. **Confirmar**
   Informe o caminho do arquivo criado e um resumo das Waves e total de MLs gerados.`,

    'implement.md': `Você é o orquestrador de implementação do trackfw. Siga o fluxo abaixo **sem pular etapas**.

## Argumento

\`$ARGUMENTS\` é opcional. Se fornecido, é usado como filtro (substring case-insensitive) sobre os nomes de arquivo das REQs.

---

## Passo 1 — Selecionar a REQ

Use Glob para listar \`docs/req/*.md\`.

- Se **nenhum arquivo encontrado**: informe que não há REQs disponíveis e sugira criar com \`/trackfw:req\`.
- Se **\`$ARGUMENTS\` foi fornecido** e filtra para exatamente uma REQ: use-a diretamente.
- Em **todos os outros casos** (sem argumento, ou argumento ambíguo): apresente a lista de REQs disponíveis e pergunte ao usuário qual deseja implementar.

Leia o conteúdo completo da REQ selecionada.

---

## Passo 2 — Encontrar ou gerar o Roadmap

Verifique se existe um roadmap vinculado à REQ buscando em \`docs/roadmaps/\` (backlog, wip, blocked, done, abandoned) por arquivo cujo nome contenha o slug da REQ.

**Se o roadmap ainda não existe:**
- Informe o usuário: "Nenhum roadmap encontrado para esta REQ. Gerando agora..."
- Execute o fluxo completo de geração do \`/trackfw:roadmap\` (leia o arquivo \`.claude/commands/trackfw/roadmap.md\` para seguir as instruções exatas), passando a REQ já selecionada — não pergunte novamente.
- Salve o roadmap gerado em \`docs/roadmaps/backlog/ROADMAP-<YYYY-MM-DD>-<slug>.md\`.

**Se o roadmap existe e já está em \`done/\` ou \`abandoned/\`:**
- Informe o usuário e pergunte se deseja criar um novo roadmap ou encerrar.

**Se o roadmap existe em \`backlog/\` ou \`blocked/\`:**
- Prossiga para o Passo 3.

**Se já está em \`wip/\`:**
- Prossiga diretamente para o Passo 4 (já está em execução).

---

## Passo 3 — Mover roadmap para WIP

Execute:
\`\`\`bash
trackfw roadmap move <nome-do-roadmap> wip
\`\`\`

Confirme que o arquivo foi movido para \`docs/roadmaps/wip/\`.

---

## Passo 4 — Ler e apresentar o plano

Leia o roadmap (agora em \`wip/\`). Apresente ao usuário:
- Título do roadmap
- Total de Waves e MLs
- Lista resumida dos MLs por Wave

Confirme: "Iniciando implementação. Vou executar cada ML em ordem e atualizar o roadmap a cada conclusão."

---

## Passo 5 — Executar cada ML em ordem

Para cada Wave (em sequência), execute os MLs da Wave:

### Para cada ML:

**5a. Anunciar:** informe qual ML está sendo executado (ex: "Executando ML-1A — Criar client.go").

**5b. Implementar:** execute as ações descritas no ML usando suas ferramentas (Read, Write, Edit, Bash). Siga exatamente os arquivos afetados, ações e critérios de aceite listados no roadmap.

**5c. Validar:** execute os comandos de validação do ML. Se falhar, corrija antes de avançar.

**5d. Atualizar o roadmap:** edite o arquivo de roadmap em \`docs/roadmaps/wip/\` substituindo o status do ML:
- \`**Status:** ⬜ Pendente\` → \`**Status:** ✅ Concluído\`

**5e. Commitar:**
\`\`\`bash
git add -A
git commit -m "feat(<escopo>): <descrição do ML>"
\`\`\`

Só avance para a próxima Wave após todos os MLs da Wave atual estarem ✅.

---

## Passo 6 — Finalizar

Quando todos os MLs estiverem ✅:

**6a.** Execute \`trackfw validate\` — deve passar com zero violations.

**6b.** Mova o roadmap para done:
\`\`\`bash
trackfw roadmap move <nome-do-roadmap> done
\`\`\`

**6c.** Faça o commit final:
\`\`\`bash
git add docs/roadmaps/
git commit -m "docs(trackfw): roadmap <nome> → done"
\`\`\`

**6d.** Informe o usuário:
\`\`\`
✅ Implementação concluída.
Roadmap: docs/roadmaps/done/<nome>.md
Próximo passo: abrir PR com gh pr create
\`\`\``,

    'architect.md': `Você é o guia de arquitetura do trackfw. Ajude o usuário a escolher a stack correta e arquitetar a aplicação em linguagem simples, acessível para times não técnicos.

## Passo 1 — Descoberta de Negócio

Faça ao usuário as seguintes perguntas em linguagem simples, uma por vez:

1. "O que sua aplicação vai fazer? Descreva em 2-3 frases como se fosse explicar para alguém de fora da TI."
2. "Quantas pessoas vão usar esse sistema simultaneamente? (< 10 pessoas / 10-100 pessoas / > 100 pessoas)"
3. "Esse sistema vai para produção de verdade ou é um protótipo para validar uma ideia?"
4. "Você precisa de login/autenticação de usuários? (Sim / Não / Não sei)"
5. "Tem alguma restrição de tecnologia ou preferência da empresa? (ex: só Java, só Microsoft, etc.)"

---

## Passo 2 — Recomendação de Stack

Com base nas respostas, escolha **UM** dos combos pré-validados:

### Combo A — Protótipo Rápido
**Quando usar:** prototipagem, validação de ideia, até ~10 usuários, sem pressão de produção.
- **Frontend:** React + Vite
- **Backend:** FastAPI (Python) ou Express (Node.js)
- **Banco:** SQLite + SQLAlchemy / Prisma
- **Auth:** JWT simples quando necessário
- **Docker:** Dockerfile básico para o backend

### Combo B — Sistema Pequeno/Médio em Produção
**Quando usar:** sistema real, 10-100 usuários, robustez e manutenibilidade.
- **Frontend:** Next.js (SSR + rotas prontas)
- **Backend:** FastAPI (Python) ou NestJS (Node.js)
- **Banco:** PostgreSQL + ORM (SQLAlchemy / Prisma / TypeORM)
- **Auth:** OAuth2 com JWT (Supabase Auth ou Auth0)
- **Docker:** docker-compose com frontend + backend + banco

### Combo C — Enterprise / Java
**Quando usar:** integração com sistemas corporativos, > 100 usuários, exigência de Java.
- **Frontend:** Angular
- **Backend:** Spring Boot
- **Banco:** PostgreSQL + Hibernate
- **Auth:** Spring Security + OAuth2 (Keycloak ou Azure AD)
- **Docker:** docker-compose com todos os serviços

Apresente o combo recomendado com explicação simples do motivo.

---

## Passo 3 — Arquitetura em Camadas (explicação simples)

Explique a arquitetura com uma metáfora de negócio:

"Pense na aplicação como um restaurante:
- **Frontend** = o salão: o que o cliente vê e interage
- **Backend** = a cozinha: onde as regras de negócio acontecem, nunca exposta diretamente
- **Banco de dados** = a despensa: onde os dados ficam guardados, acessada só pela cozinha"

Reforce as **Architecture Directives** já injetadas no CLAUDE.md deste projeto: separação em 3 camadas sem dados em memória (sempre DB + ORM), auth + Docker + .env desde o dia 1, validação em 2 camadas, contrato OpenAPI antes de codar, wave de segurança em todo roadmap e cobertura mínima de testes (60% protótipo / 80% produção).

---

## Passo 4 — Gerar o ADR de Stack

Execute \`/trackfw:adr\` com o título: \`"Stack e arquitetura em camadas — [nome do projeto]"\`

O ADR deve registrar a stack escolhida (combo e componentes), motivação baseada nas respostas, alternativas descartadas e princípios de arquitetura adotados.

---

## Passo 5 — Próximos Passos

Oriente o usuário:

\`\`\`
✅ Stack definida. Próximos passos:

1. Crie a REQ da primeira feature com /trackfw:req
2. Gere o roadmap em microlotes com /trackfw:roadmap
3. Inicie a implementação com /trackfw:implement
\`\`\``,
  }

  let created = 0
  let skipped = 0
  for (const [filename, content] of Object.entries(commands)) {
    const filePath = path.join(dir, filename)
    if (fs.existsSync(filePath)) {
      skipped++
      continue
    }
    fs.writeFileSync(filePath, content, 'utf8')
    created++
  }

  if (skipped > 0) {
    console.log(`  ✓ ${dir} (${created} slash commands criados, ${skipped} já existiam — não sobrescritos)`)
  } else {
    console.log(`  ✓ ${dir} (${created} slash commands)`)
  }
}

// ---------------------------------------------------------------------------
// AI tool installers
// ---------------------------------------------------------------------------

/**
 * installAgents — instala agentes Claude Code em ~/.claude/agents/
 * O pacote npm não embute os templates binários do Go, por isso informa
 * ao usuário que esta operação requer o binário Go instalado.
 */
async function installAgents() {
  // CLAUDE.md já tratado por generateClaudeMD via injectOrUpdateRules
  console.log('  ✓ claude (agentes — execute `trackfw install agents` com o binário Go para instalar os templates)')
}

async function installGemini(cwd = process.cwd()) {
  try {
    injectRulesForTool('gemini', cwd)
    console.log('  ✓ trackfw rules → GEMINI.md')
  } catch (e) {
    console.log(`  ⚠ gemini rules inject: ${e.message}`)
  }
}

async function installCursor(cwd = process.cwd()) {
  try {
    injectRulesForTool('cursor', cwd)
    console.log('  ✓ trackfw rules → .cursor/rules/trackfw.mdc')
  } catch (e) {
    console.log(`  ⚠ cursor rules inject: ${e.message}`)
  }
}

async function installCopilot(cwd = process.cwd()) {
  try {
    injectRulesForTool('copilot', cwd)
    console.log('  ✓ trackfw rules → .github/copilot-instructions.md')
  } catch (e) {
    console.log(`  ⚠ copilot rules inject: ${e.message}`)
  }
}

async function installWindsurf(cwd = process.cwd()) {
  try {
    injectRulesForTool('windsurf', cwd)
    console.log('  ✓ trackfw rules → .windsurfrules')
  } catch (e) {
    console.log(`  ⚠ windsurf rules inject: ${e.message}`)
  }
}

async function installAmazonQ(cwd = process.cwd()) {
  try {
    injectRulesForTool('amazonq', cwd)
    console.log('  ✓ trackfw rules → .amazonq/developer/guidelines.md')
  } catch (e) {
    console.log(`  ⚠ amazonq rules inject: ${e.message}`)
  }
}

/**
 * generateClaudeCommandsForce — re-gera todos os slash commands, sobrescrevendo arquivos existentes.
 */
function generateClaudeCommandsForce(rootDir) {
  const dir = rootDir ? path.join(rootDir, '.claude', 'commands', 'trackfw') : '.claude/commands/trackfw'
  fs.mkdirSync(dir, { recursive: true })

  const commands = {
    'adr.md': `Execute o seguinte comando bash: \`trackfw adr new "$ARGUMENTS"\`\n\nSe o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:\n\n\`\`\`\ntrackfw não está instalado. Instale com uma das opções:\n\n  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh\n  npm install -g trackfw\n  pip install trackfw\n\`\`\``,
    'req.md': `Execute o seguinte comando bash: \`trackfw req new "$ARGUMENTS"\`\n\nSe o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:\n\n\`\`\`\ntrackfw não está instalado. Instale com uma das opções:\n\n  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh\n  npm install -g trackfw\n  pip install trackfw\n\`\`\``,
    'validate.md': `Execute o seguinte comando bash: \`trackfw validate\`\n\nSe o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:\n\n\`\`\`\ntrackfw não está instalado. Instale com uma das opções:\n\n  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh\n  npm install -g trackfw\n  pip install trackfw\n\`\`\``,
    'status.md': `Execute o seguinte comando bash: \`trackfw status\`\n\nSe o comando falhar com \`trackfw: command not found\` ou similar, informe ao usuário:\n\n\`\`\`\ntrackfw não está instalado. Instale com uma das opções:\n\n  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh\n  npm install -g trackfw\n  pip install trackfw\n\`\`\``,
    'move.md': `Execute o seguinte comando bash: \`trackfw roadmap move $ARGUMENTS\`\n\nO formato esperado é: \`<nome-do-roadmap> <estado>\`\nEstados válidos: \`backlog\`, \`analyzing\`, \`wip\`, \`blocked\`, \`done\`, \`abandoned\`\n\nSe o comando falhar, instale trackfw com:\n  curl -sSfL https://github.com/kgsaran/trackfw/releases/latest/download/install.sh | sh`,
    'architect.md': `Você é o guia de arquitetura do trackfw. Ajude o usuário a escolher a stack correta e arquitetar a aplicação em linguagem simples, acessível para times não técnicos.\n\n## Passo 1 — Descoberta de Negócio\n\nFaça ao usuário as seguintes perguntas em linguagem simples, uma por vez:\n\n1. "O que sua aplicação vai fazer? Descreva em 2-3 frases como se fosse explicar para alguém de fora da TI."\n2. "Quantas pessoas vão usar esse sistema simultaneamente? (< 10 pessoas / 10-100 pessoas / > 100 pessoas)"\n3. "Esse sistema vai para produção de verdade ou é um protótipo para validar uma ideia?"\n4. "Você precisa de login/autenticação de usuários? (Sim / Não / Não sei)"\n5. "Tem alguma restrição de tecnologia ou preferência da empresa? (ex: só Java, só Microsoft, etc.)"\n\n---\n\n## Passo 2 — Recomendação de Stack\n\nCom base nas respostas, escolha **UM** dos combos pré-validados:\n\n### Combo A — Protótipo Rápido\n**Quando usar:** prototipagem, validação de ideia, até ~10 usuários, sem pressão de produção.\n- **Frontend:** React + Vite\n- **Backend:** FastAPI (Python) ou Express (Node.js)\n- **Banco:** SQLite + SQLAlchemy / Prisma\n- **Auth:** JWT simples quando necessário\n- **Docker:** Dockerfile básico para o backend\n\n### Combo B — Sistema Pequeno/Médio em Produção\n**Quando usar:** sistema real, 10-100 usuários, robustez e manutenibilidade.\n- **Frontend:** Next.js (SSR + rotas prontas)\n- **Backend:** FastAPI (Python) ou NestJS (Node.js)\n- **Banco:** PostgreSQL + ORM (SQLAlchemy / Prisma / TypeORM)\n- **Auth:** OAuth2 com JWT (Supabase Auth ou Auth0)\n- **Docker:** docker-compose com frontend + backend + banco\n\n### Combo C — Enterprise / Java\n**Quando usar:** integração com sistemas corporativos, > 100 usuários, exigência de Java.\n- **Frontend:** Angular\n- **Backend:** Spring Boot\n- **Banco:** PostgreSQL + Hibernate\n- **Auth:** Spring Security + OAuth2 (Keycloak ou Azure AD)\n- **Docker:** docker-compose com todos os serviços\n\nApresente o combo recomendado com explicação simples do motivo.\n\n---\n\n## Passo 3 — Arquitetura em Camadas (explicação simples)\n\nExplique a arquitetura com uma metáfora de negócio:\n\n"Pense na aplicação como um restaurante:\n- **Frontend** = o salão: o que o cliente vê e interage\n- **Backend** = a cozinha: onde as regras de negócio acontecem, nunca exposta diretamente\n- **Banco de dados** = a despensa: onde os dados ficam guardados, acessada só pela cozinha"\n\nReforce as **Architecture Directives** já injetadas no CLAUDE.md deste projeto: separação em 3 camadas sem dados em memória (sempre DB + ORM), auth + Docker + .env desde o dia 1, validação em 2 camadas, contrato OpenAPI antes de codar, wave de segurança em todo roadmap e cobertura mínima de testes (60% protótipo / 80% produção).\n\n---\n\n## Passo 4 — Gerar o ADR de Stack\n\nExecute \`/trackfw:adr\` com o título: \`"Stack e arquitetura em camadas — [nome do projeto]"\`\n\nO ADR deve registrar a stack escolhida (combo e componentes), motivação baseada nas respostas, alternativas descartadas e princípios de arquitetura adotados.\n\n---\n\n## Passo 5 — Próximos Passos\n\nOriente o usuário:\n\n\`\`\`\n✅ Stack definida. Próximos passos:\n\n1. Crie a REQ da primeira feature com /trackfw:req\n2. Gere o roadmap em microlotes com /trackfw:roadmap\n3. Inicie a implementação com /trackfw:implement\n\`\`\``,
  }

  for (const [filename, content] of Object.entries(commands)) {
    fs.writeFileSync(path.join(dir, filename), content, 'utf8')
  }
  console.log(`  ✓ .claude/commands/trackfw/ (${Object.keys(commands).length} slash commands sobrescritos)`)
}

/**
 * installSkillsForce — sobrescreve ~/.claude/skills/trackfw/SKILL.md sempre.
 */
function installSkillsForce() {
  const skillDir = path.join(os.homedir(), '.claude', 'skills', 'trackfw')
  fs.mkdirSync(skillDir, { recursive: true })

  const content = `---
name: trackfw
description: "trackfw — Governed Software Delivery: ADR → REQ → ROADMAP → kanban"
signature: "📦 trackfw - Governed Delivery"
---

# trackfw — Modo de Operação

Este projeto usa **trackfw** para governança de entrega de software.
Cadeia: **ADR → REQ → ROADMAP** · Estados: \`backlog / wip / blocked / done / abandoned\`

## Comandos principais

- \`trackfw context\` — contexto de trabalho atual (sempre execute primeiro)
- \`trackfw status\` — todos os artefatos e estados
- \`trackfw validate\` — valida consistência de governança
- \`trackfw roadmap move <nome> <estado>\` — transição de estado
- \`trackfw serve\` — board Kanban em http://localhost:4080

## Protocolo de agente

1. Antes de iniciar: \`trackfw context\` + ler \`docs/agents-working-context.md\`
2. Após concluir: atualizar \`docs/agents-working-context.md\`
3. Antes de PR: \`trackfw validate\` deve passar com zero violations
`

  const dest = path.join(skillDir, 'SKILL.md')
  fs.writeFileSync(dest, content, 'utf8')
  console.log(`  ✓ skill global atualizada em ${dest}`)
}

function printArchitectNextSteps(cwd) {
  const candidates = [
    { file: 'CLAUDE.md',                              cmd: 'claude' },
    { file: '.cursor/rules/trackfw.mdc',              cmd: 'cursor .' },
    { file: '.windsurfrules',                         cmd: 'windsurf .' },
    { file: '.github/copilot-instructions.md',        cmd: 'code . (Copilot)' },
    { file: '.amazonq/developer/guidelines.md',       cmd: 'code . (Amazon Q)' },
    { file: 'GEMINI.md',                              cmd: 'gemini' },
    { file: 'AGENTS.md',                              cmd: 'codex' },
  ]

  const detected = candidates.filter(t => {
    try { return fs.existsSync(path.join(cwd, t.file)) } catch { return false }
  })

  const tools = detected.length > 0 ? detected : [{ cmd: 'claude' }]

  console.log()
  console.log('Próximo passo — inicie com o guia de arquitetura:')
  console.log()
  for (const t of tools) {
    console.log(`  ${t.cmd}`)
  }
  console.log()
  console.log('  Execute /trackfw:architect no chat do seu assistente de IA.')
  console.log()
}

module.exports = {
  GOV_DIRS,
  scaffold,
  writeTrackfwConfig,
  generateValidateScript,
  generateAttentionScripts,
  generateCIWorkflow,
  generateGitHooks,
  generateCommitMsgHook,
  generateClaudeMD,
  generateClaudeCommands,
  generateClaudeCommandsForce,
  installSkillsForce,
  installAgents,
  installGemini,
  installCursor,
  installCopilot,
  installWindsurf,
  installAmazonQ,
  injectRulesForTool,
  injectRulesDetected,
  trackfwRulesBlock,
  printArchitectNextSteps,
}
