package generators

import (
	"fmt"
	"strings"
	"time"
)

func generateClaudeMD(cfg Config) error {
	var sb strings.Builder

	projectName := cfg.ProjectName
	if projectName == "" {
		projectName = "my-project"
	}

	sb.WriteString(fmt.Sprintf("# %s — Claude Code Instructions\n\n", projectName))
	sb.WriteString(fmt.Sprintf("> Generated by trackfw on %s. Update this file as the project evolves.\n\n", time.Now().Format("2006-01-02")))

	sb.WriteString("## Project overview\n\n")
	sb.WriteString("<!-- Describe what this project does in 2-3 sentences. -->\n\n")

	sb.WriteString("## Governance chain\n\n")
	sb.WriteString("```\nADR → REQ → ROADMAP → backlog / analyzing / wip / blocked / done / abandoned\n```\n\n")

	sb.WriteString("## Agent rules (mandatory)\n\n")
	sb.WriteString("These rules apply to every agent or AI assistant working in this project:\n\n")
	sb.WriteString("1. **Never start coding without a REQ and a ROADMAP.** If none exists, create them first.\n")
	sb.WriteString("2. **Use `/trackfw:implement <req-slug>` to start any implementation.** This skill orchestrates the full flow automatically: finds or generates the roadmap, moves it to `wip/`, executes each ML, updates the roadmap, and moves to `done/`.\n")
	sb.WriteString("3. **Only one roadmap in `wip/` at a time.** Before starting a new one, complete or move to `blocked/` the current one.\n")
	sb.WriteString("4. **ML lifecycle — mandatory:** When starting a ML, change `**Status:** ⬜ Pendente` → `**Status:** 🔄 Em andamento` and commit the roadmap. When completing, change to `**Status:** ✅ Concluído` and include in the ML commit. When analyzing a roadmap before starting, move it from `backlog/` to `analyzing/`; only move to `wip/` when actually coding.\n")
	sb.WriteString("5. **Run `trackfw validate` before every commit.** Zero violations required.\n")
	sb.WriteString("6. **ADRs before decisions.** Any architectural or technical decision must have an ADR (`/trackfw:adr`).\n")
	sb.WriteString("7. **Use `/trackfw:architect` to define stack and architecture before the first REQ.**\n\n")

	sb.WriteString("## Slash commands (Claude Code)\n\n")
	sb.WriteString("| Command | When to use |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `/trackfw:implement <req>` | **Start here** — orchestrates full implementation flow |\n")
	sb.WriteString("| `/trackfw:adr <title>` | Before any architectural decision |\n")
	sb.WriteString("| `/trackfw:req <title>` | Before any implementation work |\n")
	sb.WriteString("| `/trackfw:roadmap <req>` | Generate AI roadmap from a REQ |\n")
	sb.WriteString("| `/trackfw:move <name> <state>` | Move roadmap between states manually |\n")
	sb.WriteString("| `/trackfw:validate` | Run governance validation |\n")
	sb.WriteString("| `/trackfw:status` | Check what is in flight |\n")
	sb.WriteString("| `/trackfw:architect` | Guide stack and architecture decisions |\n\n")

	sb.WriteString("## CLI commands (terminal / CI)\n\n")
	sb.WriteString("| Command | When to use |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `trackfw adr new \"title\"` | Create ADR |\n")
	sb.WriteString("| `trackfw req new \"title\"` | Create REQ |\n")
	sb.WriteString("| `trackfw roadmap new` | Create empty roadmap linked to a REQ |\n")
	sb.WriteString("| `trackfw roadmap move <name> <state>` | Move roadmap state |\n")
	sb.WriteString("| `trackfw validate` | Governance validation gate |\n")
	sb.WriteString("| `trackfw status` | Show governance status |\n\n")

	sb.WriteString("## Architecture Directives (mandatory)\n\n")
	sb.WriteString("1. **3-layer separation** — frontend / backend / database. Never mix concerns.\n")
	sb.WriteString("2. **No in-memory data** — always database + ORM. Never arrays/globals for persistence.\n")
	sb.WriteString("3. **Auth from day 1** — never defer; refactoring auth later is very costly.\n")
	sb.WriteString("4. **Docker + .env from day 1** — containerize early; all config via env vars, never hardcoded.\n")
	sb.WriteString("5. **2-layer validation** — frontend (UX feedback) + backend (security guard). Never only one.\n")
	sb.WriteString("6. **API-first** — define OpenAPI contract before coding frontend/backend integration.\n")
	sb.WriteString("7. **Security wave** — include a red-team review wave at the end of every feature roadmap.\n")
	sb.WriteString("8. **Test coverage** — TDD for critical business logic; min 60% (prototype) / 80% (production).\n\n")

	// Frontend section
	if cfg.Frontend != "" && cfg.Frontend != "none" {
		pm := cfg.PkgManager
		if pm == "" || pm == "none" {
			pm = "npm"
		}
		sb.WriteString("## Frontend\n\n")
		sb.WriteString(fmt.Sprintf("Stack: %s\n", cfg.Frontend))
		sb.WriteString(fmt.Sprintf("Package manager: %s\n\n", pm))
		sb.WriteString("Build commands:\n")
		sb.WriteString(fmt.Sprintf("  %s run build     # build\n", pm))
		sb.WriteString(fmt.Sprintf("  %s run dev       # dev server\n", pm))
		sb.WriteString(fmt.Sprintf("  %s run test      # tests\n\n", pm))
		sb.WriteString("Rules:\n")
		sb.WriteString(fmt.Sprintf("- Build must pass (`%s run build`) before marking any ML as done\n", pm))
		sb.WriteString("- Run `trackfw validate` before committing frontend changes\n\n")
	}

	// Backend section
	if cfg.Backend != "" && cfg.Backend != "none" {
		buildCmd, testCmd, lintCmd := backendCommands(cfg)
		sb.WriteString("## Backend\n\n")
		sb.WriteString(fmt.Sprintf("Stack: %s\n\n", cfg.Backend))
		sb.WriteString("Build commands:\n")
		sb.WriteString(fmt.Sprintf("  %s   # build / compile check\n", buildCmd))
		sb.WriteString(fmt.Sprintf("  %s   # tests\n", testCmd))
		sb.WriteString(fmt.Sprintf("  %s   # lint / vet\n\n", lintCmd))
		sb.WriteString("Rules:\n")
		sb.WriteString("- Build must pass before marking any ML as done\n")
		sb.WriteString("- Run `trackfw validate` before committing backend changes\n\n")
	}

	// Pre-commit checklist
	sb.WriteString("## Pre-commit checklist\n\n")
	sb.WriteString("Before every commit:\n")
	sb.WriteString("- [ ] `trackfw validate` passes with zero violations\n")
	if cfg.Backend != "" && cfg.Backend != "none" {
		buildCmd, _, _ := backendCommands(cfg)
		sb.WriteString(fmt.Sprintf("- [ ] `%s` passes\n", buildCmd))
	}
	if cfg.Frontend != "" && cfg.Frontend != "none" {
		pm := cfg.PkgManager
		if pm == "" || pm == "none" {
			pm = "npm"
		}
		sb.WriteString(fmt.Sprintf("- [ ] `%s run build` passes\n", pm))
	}
	sb.WriteString("\n")

	// Git hooks section
	sb.WriteString("## Git hooks\n\n")
	switch cfg.Hooks {
	case "husky":
		sb.WriteString("Git hook configured in `.husky/pre-commit` — runs `trackfw validate` automatically.\n\n")
	case "lefthook":
		sb.WriteString("Git hook configured in `lefthook.yml` — runs `trackfw validate` automatically.\n\n")
	default:
		sb.WriteString("No git hook configured. Run `trackfw validate` manually before every commit.\n\n")
	}

	// CI gate section
	sb.WriteString("## CI gate\n\n")
	switch cfg.CI {
	case "github-actions":
		sb.WriteString("`.github/workflows/trackfw-gate.yml` runs `trackfw validate` on every pull request to main.\n")
	case "gitlab-ci":
		sb.WriteString("`.gitlab-ci-trackfw.yml` runs `trackfw validate` on every merge request.\n")
	default:
		sb.WriteString("No CI gate configured.\n")
	}

	if err := injectOrUpdateRules("CLAUDE.md", sb.String()); err != nil {
		return fmt.Errorf("updating CLAUDE.md: %w", err)
	}
	fmt.Println("  ✓ CLAUDE.md")
	return nil
}

// backendCommands retorna (buildCmd, testCmd, lintCmd) para o backend configurado.
func backendCommands(cfg Config) (string, string, string) {
	pm := cfg.PkgManager
	if pm == "" || pm == "none" {
		pm = "npm"
	}
	switch cfg.Backend {
	case "go":
		return "go build ./...", "go test ./...", "go vet ./..."
	case "java":
		return "mvn package -q", "mvn test", "mvn compile -q"
	case "node":
		return pm + " run build", pm + " test", pm + " run lint"
	case "python":
		return "python3 -c \"import pathlib, py_compile; [py_compile.compile(str(p), doraise=True) for p in pathlib.Path('.').rglob('*.py') if '.venv' not in p.parts and 'venv' not in p.parts]\"",
			"python -m pytest",
			"ruff check ."
	default:
		return "", "", ""
	}
}
