package generators

import (
	"fmt"
	"strings"
	"time"
)

// GlobalADRsDirective é a diretiva obrigatória para instruir os agentes sobre ADRs globais.
const GlobalADRsDirective = "Obrigatório: Inspecione e respeite todos os ADRs globais nos diretórios listados em adr_dirs (inclusive caminhos ~/...) antes de propor alterações de arquitetura."

func generateClaudeMD(cfg Config) error {
	var sb strings.Builder

	projectName := cfg.ProjectName
	if projectName == "" {
		projectName = "my-project"
	}

	sb.WriteString(fmt.Sprintf("# %s — Claude Code Instructions\n\n", projectName))
	sb.WriteString(fmt.Sprintf("> Generated by trackfw on %s. Update this file as the project evolves.\n\n", time.Now().Format("2006-01-02")))

	sb.WriteString("## Project overview\n\n")
	sb.WriteString("<!-- Describe what this project does in 2-3 sentences. -->\n\n")

	sb.WriteString("## Governance chain\n\n")
	sb.WriteString("```\nADR → REQ → ROADMAP → backlog / analyzing / wip / blocked / done / abandoned\n```\n\n")

	sb.WriteString("## Agent rules (mandatory)\n\n")
	sb.WriteString("These rules apply to every agent or AI assistant working in this project:\n\n")
	sb.WriteString("1. **Never start coding without a REQ and a ROADMAP.** If none exists, create them first.\n")
	sb.WriteString("2. **Use `/trackfw:implement <req-slug>` to start any implementation.** This skill orchestrates the full flow automatically: finds or generates the roadmap, moves it to `wip/`, executes each ML, updates the roadmap, and moves to `done/`.\n")
	sb.WriteString("3. **Only one roadmap in `wip/` at a time.** Before starting a new one, complete or move to `blocked/` the current one.\n")
	sb.WriteString("4. **ML lifecycle — mandatory:** When starting a ML, change `**Status:** ⬜ Pendente` → `**Status:** 🔄 Em andamento` and commit the roadmap. When completing, change to `**Status:** ✅ Concluído` and include in the ML commit. When analyzing a roadmap before starting, move it from `backlog/` to `analyzing/`; only move to `wip/` when actually coding.\n")
	sb.WriteString("5. **Run `trackfw validate` before every commit.** Zero violations required.\n")
	sb.WriteString("6. **ADRs before decisions.** Any architectural or technical decision must have an ADR (`/trackfw:adr`).\n")
	sb.WriteString("6a. **Usar `/trackfw:architect` para definir stack e arquitetura antes da primeira REQ.**\n")
	sb.WriteString("7. **" + GlobalADRsDirective + "**\n\n")

	sb.WriteString("## Slash commands (Claude Code)\n\n")
	sb.WriteString("| Command | When to use |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `/trackfw:implement <req>` | **Start here** — orchestrates full implementation flow |\n")
	sb.WriteString("| `/trackfw:adr <title>` | Before any architectural decision |\n")
	sb.WriteString("| `/trackfw:req <title>` | Before any implementation work |\n")
	sb.WriteString("| `/trackfw:roadmap <req>` | Generate AI roadmap from a REQ |\n")
	sb.WriteString("| `/trackfw:move <name> <state>` | Move roadmap between states manually |\n")
	sb.WriteString("| `/trackfw:validate` | Run governance validation |\n")
	sb.WriteString("| `/trackfw:status` | Check what is in flight |\n")
	sb.WriteString("| `/trackfw:architect` | Guide stack and architecture decisions |\n")
	sb.WriteString("| `/trackfw:barrier` | Run the wave-release checklist before liberating the next wave |\n\n")

	sb.WriteString("## CLI commands (terminal / CI)\n\n")
	sb.WriteString("| Command | When to use |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `trackfw adr new \"title\"` | Create ADR |\n")
	sb.WriteString("| `trackfw req new \"title\"` | Create REQ |\n")
	sb.WriteString("| `trackfw roadmap new` | Create empty roadmap linked to a REQ |\n")
	sb.WriteString("| `trackfw roadmap move <name> <state>` | Move roadmap state |\n")
	sb.WriteString("| `trackfw validate` | Governance validation gate |\n")
	sb.WriteString("| `trackfw status` | Show governance status |\n\n")

	sb.WriteString("## Architecture Directives (mandatory)\n\n")
	sb.WriteString("1. **3-layer separation** — frontend / backend / database. Never mix concerns.\n")
	sb.WriteString("2. **No in-memory data** — always database + ORM. Never arrays/globals for persistence.\n")
	sb.WriteString("3. **Auth from day 1** — never defer; refactoring auth later is very costly.\n")
	sb.WriteString("4. **Docker + .env from day 1** — containerize early; all config via env vars, never hardcoded.\n")
	sb.WriteString("5. **2-layer validation** — frontend (UX feedback) + backend (security guard). Never only one.\n")
	sb.WriteString("6. **API-first** — define OpenAPI contract before coding frontend/backend integration.\n")
	sb.WriteString("7. **Threat model waves** — every feature roadmap opens with a Wave 0 threat model (before implementation) and closes with a red-team review wave (before release).\n")
	sb.WriteString("8. **Test coverage** — TDD for critical business logic; min 60% (prototype) / 80% (production).\n\n")

	// Frontend section
	if cfg.Frontend != "" && cfg.Frontend != "none" {
		pm := cfg.PkgManager
		if pm == "" || pm == "none" {
			pm = "npm"
		}
		sb.WriteString("## Frontend\n\n")
		sb.WriteString(fmt.Sprintf("Stack: %s\n", cfg.Frontend))
		sb.WriteString(fmt.Sprintf("Package manager: %s\n\n", pm))
		sb.WriteString("Build commands:\n")
		sb.WriteString(fmt.Sprintf("  %s run build     # build\n", pm))
		sb.WriteString(fmt.Sprintf("  %s run dev       # dev server\n", pm))
		sb.WriteString(fmt.Sprintf("  %s run test      # tests\n\n", pm))
		sb.WriteString("Rules:\n")
		sb.WriteString(fmt.Sprintf("- Build must pass (`%s run build`) before marking any ML as done\n", pm))
		sb.WriteString("- Run `trackfw validate` before committing frontend changes\n\n")
	}

	// Backend section
	if cfg.Backend != "" && cfg.Backend != "none" {
		buildCmd, testCmd, lintCmd := backendCommands(cfg)
		sb.WriteString("## Backend\n\n")
		sb.WriteString(fmt.Sprintf("Stack: %s\n\n", cfg.Backend))
		sb.WriteString("Build commands:\n")
		sb.WriteString(fmt.Sprintf("  %s   # build / compile check\n", buildCmd))
		sb.WriteString(fmt.Sprintf("  %s   # tests\n", testCmd))
		sb.WriteString(fmt.Sprintf("  %s   # lint / vet\n\n", lintCmd))
		sb.WriteString("Rules:\n")
		sb.WriteString("- Build must pass before marking any ML as done\n")
		sb.WriteString("- Run `trackfw validate` before committing backend changes\n\n")
	}

	// Pre-commit checklist
	sb.WriteString("## Pre-commit checklist\n\n")
	sb.WriteString("Before every commit:\n")
	sb.WriteString("- [ ] `trackfw validate` passes with zero violations\n")
	if cfg.Backend != "" && cfg.Backend != "none" {
		buildCmd, _, _ := backendCommands(cfg)
		sb.WriteString(fmt.Sprintf("- [ ] `%s` passes\n", buildCmd))
	}
	if cfg.Frontend != "" && cfg.Frontend != "none" {
		pm := cfg.PkgManager
		if pm == "" || pm == "none" {
			pm = "npm"
		}
		sb.WriteString(fmt.Sprintf("- [ ] `%s run build` passes\n", pm))
	}
	sb.WriteString("\n")

	// Git hooks section
	sb.WriteString("## Git hooks\n\n")
	switch cfg.Hooks {
	case "husky":
		sb.WriteString("Git hook configured in `.husky/pre-commit` — runs `trackfw validate` automatically.\n\n")
	case "lefthook":
		sb.WriteString("Git hook configured in `lefthook.yml` — runs `trackfw validate` automatically.\n\n")
	default:
		sb.WriteString("No git hook configured. Run `trackfw validate` manually before every commit.\n\n")
	}

	// CI gate section
	sb.WriteString("## CI gate\n\n")
	switch cfg.CI {
	case "github-actions":
		sb.WriteString("`.github/workflows/trackfw-gate.yml` runs `trackfw validate` on every pull request to main.\n")
	case "gitlab-ci":
		sb.WriteString("`.gitlab-ci-trackfw.yml` runs `trackfw validate` on every merge request.\n")
	default:
		sb.WriteString("No CI gate configured.\n")
	}

	// Harness sections — derived from project governance conventions
	sb.WriteString("\n## Branch strategy\n\n")
	sb.WriteString("One active branch at a time. Name it `feat/<slug>`, `fix/<slug>` or `refactor/<slug>`. ")
	sb.WriteString("Before creating a new branch, verify no other is genuinely open: run `git fetch origin --prune`, ")
	sb.WriteString("then `git branch -r --no-merged origin/main`, then for each candidate `git diff origin/main <branch> --stat`. ")
	sb.WriteString("An empty diff means it was squash-merged — ignore it. ")
	sb.WriteString("Squash merges do not mark a branch as merged, so `--no-merged` alone is not evidence. ")
	sb.WriteString("If the branch is stale and the diff looks inflated by main's own evolution, ")
	sb.WriteString("compare only the files the branch itself touched since the merge base.\n\n")

	sb.WriteString("## Definition of done\n\n")
	sb.WriteString("Green build and tests do not close a microbatch. ")
	sb.WriteString("It is done when the requirement and the roadmap sit in the correct state folder, ")
	sb.WriteString("their declared status matches that folder, the final validation is recorded with evidence, ")
	sb.WriteString("no duplicate copy remains in another state, and `trackfw validate` reports no violations.\n\n")

	sb.WriteString("## Requirement scope\n\n")
	sb.WriteString("Every requirement must declare an explicit negative scope: what must not be implemented. ")
	sb.WriteString("Boundaries prevent an implementing agent from inventing work.\n\n")

	sb.WriteString("## State requirements\n\n")
	sb.WriteString("`blocked` requires a reason and an owner. ")
	sb.WriteString("`abandoned` requires a reason and a successor. ")
	sb.WriteString("`wip` must reflect work that is genuinely active; ")
	sb.WriteString("anything stalled moves to `blocked` or `abandoned` instead of rotting in `wip`.\n\n")

	sb.WriteString("## Roadmap format\n\n")
	sb.WriteString("Organize work as waves of microbatches. ")
	sb.WriteString("A wave groups microbatches that can run in parallel; a barrier separates waves. ")
	sb.WriteString("Microbatches sharing any file — including generated trees and build outputs — must be sequential, ")
	sb.WriteString("and the reason is documented. ")
	sb.WriteString("Each microbatch declares exact files, exact actions, measurable acceptance criteria and exact validation commands, ")
	sb.WriteString("so that a small model can execute it without guessing.\n\n")

	sb.WriteString("## When governance is not required\n\n")
	sb.WriteString("A closed list of exemptions: a typo or local variable rename; a documentation-only change; ")
	sb.WriteString("a configuration tweak with no runtime effect; a direct revert; ")
	sb.WriteString("answering a question or reviewing without changes. ")
	sb.WriteString("Additionally, when the user reports a concrete bug, fix it directly and do not open an architectural analysis for it. ")
	sb.WriteString("**This section takes precedence over the general rule that requires a requirement and a roadmap.** ")
	sb.WriteString("Anything touching business logic, an API contract, a data schema, authentication or authorization, ")
	sb.WriteString("localization, or user-facing behavior always requires governance, regardless of how few files it touches.\n\n")

	sb.WriteString("## Production incidents\n\n")
	sb.WriteString("Inspect the live environment before proposing a fix: real variables, active credentials, ")
	sb.WriteString("granted permissions, running processes. ")
	sb.WriteString("Confirm the root cause against real evidence, then implement the smallest fix. ")
	sb.WriteString("Never edit static configuration files as a response to a root cause that has not been confirmed in the running environment.\n\n")

	sb.WriteString("## Iterative prototyping\n\n")
	sb.WriteString("For complex or uncertain user-facing work, validate the concept with a disposable, isolated prototype ")
	sb.WriteString("that the user reviews visually, and only then write the decision record and the production roadmap. ")
	sb.WriteString("Build and test success is not evidence that an interface is right.\n\n")

	sb.WriteString("## Autopilot\n\n")
	sb.WriteString("Ask everything you need before starting. ")
	sb.WriteString("Once started, do not interrupt for confirmations that could have been anticipated. ")
	sb.WriteString("Decide low-risk details autonomously following existing project conventions, ")
	sb.WriteString("and record autonomous decisions in the commit message.\n")

	sb.WriteString("\n## Architect responses\n\n")
	sb.WriteString("Default: what changed · what was decided · what is needed from you. Three to five lines.\n\n")
	sb.WriteString("Scale up only on these three triggers, and only on them: a **blocker** that stops the next wave; ")
	sb.WriteString("a **pending user decision** that cannot be inferred from context; ")
	sb.WriteString("an **error the architect made** that cannot be self-corrected.\n\n")
	sb.WriteString("Never cut, even when short: measured evidence (command and result), barrier verdict, decision taken and why. ")
	sb.WriteString("A response that buries a blocker in paragraph seven produced the same effect as not reporting it.\n\n")
	sb.WriteString("Cut: restating what an executor already reported, re-explaining reasoning already given, ")
	sb.WriteString("recapping state that has not changed, closing praise. ")
	sb.WriteString("Tables and code blocks only when they replace prose, never when they add to it.\n\n")
	sb.WriteString("Depth is on demand from the user.\n")

	if err := injectOrUpdateRules("CLAUDE.md", sb.String(), "."); err != nil {
		return fmt.Errorf("updating CLAUDE.md: %w", err)
	}
	fmt.Println("  ✓ CLAUDE.md")
	return nil
}

// backendCommands retorna (buildCmd, testCmd, lintCmd) para o backend configurado.
func backendCommands(cfg Config) (string, string, string) {
	pm := cfg.PkgManager
	if pm == "" || pm == "none" {
		pm = "npm"
	}
	switch cfg.Backend {
	case "go":
		return "go build ./...", "go test ./...", "go vet ./..."
	case "java":
		return "mvn package -q", "mvn test", "mvn compile -q"
	case "node":
		return pm + " run build", pm + " test", pm + " run lint"
	case "python":
		return "python3 -c \"import pathlib, py_compile; [py_compile.compile(str(p), doraise=True) for p in pathlib.Path('.').rglob('*.py') if '.venv' not in p.parts and 'venv' not in p.parts]\"",
			"python -m pytest",
			"ruff check ."
	default:
		return "", "", ""
	}
}
