package generators

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/kgsaran/trackfw/internal/integrations"
)

// TestValidateScriptMembership verifies that checkValidateScriptArtifact accepts
// both the Go/Node form and Python's fixed form, and refuses a near-miss that
// matches neither.
//
// This test is the durability anchor for the set-membership decision (2026-08-27):
// if buildValidateScript or pythonValidateScriptForm changes, this test breaks and
// forces a conscious update of the membership set.
func TestValidateScriptMembership(t *testing.T) {
	cfg := Config{} // no backend/frontend — same as this repo's trackfw.yaml
	goNodeForm := buildValidateScript(cfg)
	pythonForm := pythonValidateScriptForm

	cases := []struct {
		name    string
		content string
		mode    os.FileMode
		wantNil bool // true = accepted (nil finding), false = accused
	}{
		{
			name:    "Go/Node form accepted with 0755",
			content: goNodeForm,
			mode:    0o755,
			wantNil: true,
		},
		{
			name:    "Python form accepted with 0755",
			content: pythonForm,
			mode:    0o755,
			wantNil: true,
		},
		{
			name:    "near-miss Go form (set -x instead of set -e) refused",
			content: "#!/usr/bin/env sh\n# trackfw governance gate — generated by trackfw init\nset -x\n\necho \"→ trackfw: validating governance...\"\ntrackfw validate\n\n\necho \"✓ all checks passed.\"\n",
			mode:    0o755,
			wantNil: false,
		},
		{
			name:    "hand-edited content refused",
			content: "trackfw validate\n",
			mode:    0o755,
			wantNil: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
				t.Fatal(err)
			}
			p := filepath.Join(dir, "scripts/trackfw-validate.sh")
			if err := os.WriteFile(p, []byte(tc.content), tc.mode); err != nil {
				t.Fatal(err)
			}
			if err := os.Chmod(p, tc.mode); err != nil {
				t.Fatal(err)
			}
			finding := checkValidateScriptArtifact(p, "scripts/trackfw-validate.sh", cfg)
			if tc.wantNil && finding != nil {
				t.Errorf("expected no finding but got: %+v", finding)
			}
			if !tc.wantNil && finding == nil {
				t.Errorf("expected a finding but got nil")
			}
		})
	}
}

// TestValidateScriptMembership_Missing verifies that a missing file produces
// scaffold-missing, not scaffold-divergent.
func TestValidateScriptMembership_Missing(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{}
	finding := checkValidateScriptArtifact(
		filepath.Join(dir, "scripts/trackfw-validate.sh"),
		"scripts/trackfw-validate.sh",
		cfg,
	)
	if finding == nil {
		t.Fatal("expected scaffold-missing finding for absent file, got nil")
	}
	if finding.FindingKind != "scaffold-missing" {
		t.Errorf("expected finding.FindingKind=scaffold-missing, got %q", finding.FindingKind)
	}
}

// TestWrongModeDetection_ValidateScript verifies AC2/AC3: content correct but execute
// bit missing → scaffold-wrong-mode (not scaffold-divergent).
func TestWrongModeDetection_ValidateScript(t *testing.T) {
	cfg := Config{}
	goNodeForm := buildValidateScript(cfg)

	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "scripts/trackfw-validate.sh")
	// Write with correct content but wrong mode (0644 — no execute bit).
	if err := os.WriteFile(p, []byte(goNodeForm), 0o644); err != nil {
		t.Fatal(err)
	}
	// Ensure mode is exactly 0644 regardless of umask.
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkValidateScriptArtifact(p, "scripts/trackfw-validate.sh", cfg)
	if execBitRepresentavelPara(t, p) {
		if finding == nil {
			t.Fatal("expected scaffold-wrong-mode finding for 0644 script, got nil")
		}
		if finding.FindingKind != integrations.DoctorScaffoldWrongMode {
			t.Errorf("expected scaffold-wrong-mode, got %q", finding.FindingKind)
		}
	} else {
		execBitNaoExercitado(t, p)
	}
}

// TestWrongModeDetection_StaticScript verifies AC2/AC3 for a static script.
func TestWrongModeDetection_StaticScript(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	relPath := "scripts/trackfw-attention-signal.sh"
	p := filepath.Join(dir, relPath)
	// Write correct content but wrong mode.
	if err := os.WriteFile(p, []byte(attentionSignalScript), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(attentionSignalScript), true, true)
	if execBitRepresentavelPara(t, p) {
		if finding == nil {
			t.Fatal("expected scaffold-wrong-mode finding, got nil")
		}
		if finding.FindingKind != integrations.DoctorScaffoldWrongMode {
			t.Errorf("expected scaffold-wrong-mode, got %q", finding.FindingKind)
		}
	} else {
		execBitNaoExercitado(t, p)
	}
}

// TestWrongModeDetection_ContentDivergence_TakesPrecedence verifies that a file
// with both wrong content and wrong mode produces scaffold-divergent, not
// scaffold-wrong-mode (content divergence takes precedence — AC3).
func TestWrongModeDetection_ContentDivergence_TakesPrecedence(t *testing.T) {
	// No platform guard here, on purpose: checkScaffoldArtifact checks
	// content BEFORE the execute bit (bytes.Equal at scaffold_doctor.go
	// precedes the CurrentGOOS/execBitPresent branch), so this assertion
	// never touches the execute bit and holds unconditionally on every
	// platform. A t.Skip("execute bit not applicable...") here was
	// leftover copy-paste from the neighboring mode tests, not a real
	// platform dependency — see the ML-1A scan report.
	dir := t.TempDir()
	relPath := "scripts/trackfw-attention-signal.sh"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	// Wrong content AND wrong mode.
	if err := os.WriteFile(p, []byte("wrong content\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(attentionSignalScript), true, true)
	if finding == nil {
		t.Fatal("expected a finding, got nil")
	}
	if finding.FindingKind != integrations.DoctorScaffoldDivergent {
		t.Errorf("expected scaffold-divergent (content takes precedence), got %q", finding.FindingKind)
	}
}

// TestExecBitFalse_NotAccusedForMissingBit verifies AC4/AC11: an artifact with
// execBit=false is never accused of a missing execute bit, even when at 0644.
func TestExecBitFalse_NotAccusedForMissingBit(t *testing.T) {
	dir := t.TempDir()
	relPath := ".claude/commands/trackfw/example.md"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	content := "# example slash command\n"
	// Write with 0644 (no execute bit) — correct for this artifact type.
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(content), true, false)
	if finding != nil {
		t.Errorf("expected no finding for 0644 non-executable artifact, got: %+v", finding)
	}
}

// TestExecBitPresent_UmaskNarrowedMode_Accepted verifies AC10: a file with mode 0700
// (umask 077 on 0755) has the owner-execute bit set and must NOT be accused.
func TestExecBitPresent_UmaskNarrowedMode_Accepted(t *testing.T) {
	dir := t.TempDir()
	relPath := "scripts/trackfw-credential-guard.sh"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(credentialGuardScript), 0o755); err != nil {
		t.Fatal(err)
	}
	// Narrow the mode to 0700 — simulates umask 077.
	if err := os.Chmod(p, 0o700); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(credentialGuardScript), true, true)
	if execBitRepresentavelPara(t, p) {
		if finding != nil {
			t.Errorf("expected no finding for 0700 (execute bit present), got: %+v", finding)
		}
	} else {
		execBitNaoExercitado(t, p)
	}
}

// TestWindowsPlatformGuard verifies AC5: on "windows", mode check is suppressed
// even if the file has 0644 and correct content → no scaffold-wrong-mode finding.
func TestWindowsPlatformGuard(t *testing.T) {
	// Override CurrentGOOS to simulate Windows.
	prev := CurrentGOOS
	CurrentGOOS = "windows"
	defer func() { CurrentGOOS = prev }()

	dir := t.TempDir()
	relPath := "scripts/trackfw-attention-signal.sh"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	// Correct content, wrong mode — on Windows this must be silent.
	if err := os.WriteFile(p, []byte(attentionSignalScript), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(attentionSignalScript), true, true)
	if finding != nil {
		t.Errorf("expected no finding on Windows (mode check suppressed), got: %+v", finding)
	}
}

// TestWindowsPlatformGuard_ValidateScript verifies AC5 for checkValidateScriptArtifact.
func TestWindowsPlatformGuard_ValidateScript(t *testing.T) {
	prev := CurrentGOOS
	CurrentGOOS = "windows"
	defer func() { CurrentGOOS = prev }()

	cfg := Config{}
	goNodeForm := buildValidateScript(cfg)

	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "scripts/trackfw-validate.sh")
	if err := os.WriteFile(p, []byte(goNodeForm), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkValidateScriptArtifact(p, "scripts/trackfw-validate.sh", cfg)
	if finding != nil {
		t.Errorf("expected no finding on Windows (mode check suppressed), got: %+v", finding)
	}
}
