package generators

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kgsaran/trackfw/internal/config"
	"github.com/kgsaran/trackfw/internal/integrations"
)

// TestValidateScriptMembership verifies that checkValidateScriptArtifact accepts
// both the Go/Node form and Python's fixed form, and refuses a near-miss that
// matches neither.
//
// This test is the durability anchor for the set-membership decision (2026-08-27):
// if buildValidateScript or pythonValidateScriptForm changes, this test breaks and
// forces a conscious update of the membership set.
func TestValidateScriptMembership(t *testing.T) {
	cfg := Config{} // no backend/frontend — same as this repo's trackfw.yaml
	goNodeForm := buildValidateScript(cfg)
	pythonForm := pythonValidateScriptForm

	cases := []struct {
		name    string
		content string
		mode    os.FileMode
		wantNil bool // true = accepted (nil finding), false = accused
	}{
		{
			name:    "Go/Node form accepted with 0755",
			content: goNodeForm,
			mode:    0o755,
			wantNil: true,
		},
		{
			name:    "Python form accepted with 0755",
			content: pythonForm,
			mode:    0o755,
			wantNil: true,
		},
		{
			name:    "near-miss Go form (set -x instead of set -e) refused",
			content: "#!/usr/bin/env sh\n# trackfw governance gate — generated by trackfw init\nset -x\n\necho \"→ trackfw: validating governance...\"\ntrackfw validate\n\n\necho \"✓ all checks passed.\"\n",
			mode:    0o755,
			wantNil: false,
		},
		{
			name:    "hand-edited content refused",
			content: "trackfw validate\n",
			mode:    0o755,
			wantNil: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
				t.Fatal(err)
			}
			p := filepath.Join(dir, "scripts/trackfw-validate.sh")
			if err := os.WriteFile(p, []byte(tc.content), tc.mode); err != nil {
				t.Fatal(err)
			}
			if err := os.Chmod(p, tc.mode); err != nil {
				t.Fatal(err)
			}
			finding := checkValidateScriptArtifact(p, "scripts/trackfw-validate.sh", cfg)
			if tc.wantNil && finding != nil {
				t.Errorf("expected no finding but got: %+v", finding)
			}
			if !tc.wantNil && finding == nil {
				t.Errorf("expected a finding but got nil")
			}
		})
	}
}

// TestValidateScriptMembership_Missing verifies that a missing file produces
// scaffold-missing, not scaffold-divergent.
func TestValidateScriptMembership_Missing(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{}
	finding := checkValidateScriptArtifact(
		filepath.Join(dir, "scripts/trackfw-validate.sh"),
		"scripts/trackfw-validate.sh",
		cfg,
	)
	if finding == nil {
		t.Fatal("expected scaffold-missing finding for absent file, got nil")
	}
	if finding.FindingKind != "scaffold-missing" {
		t.Errorf("expected finding.FindingKind=scaffold-missing, got %q", finding.FindingKind)
	}
}

// TestWrongModeDetection_ValidateScript verifies AC2/AC3: content correct but execute
// bit missing → scaffold-wrong-mode (not scaffold-divergent).
func TestWrongModeDetection_ValidateScript(t *testing.T) {
	cfg := Config{}
	goNodeForm := buildValidateScript(cfg)

	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "scripts/trackfw-validate.sh")
	// Write with correct content but wrong mode (0644 — no execute bit).
	if err := os.WriteFile(p, []byte(goNodeForm), 0o644); err != nil {
		t.Fatal(err)
	}
	// Ensure mode is exactly 0644 regardless of umask.
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkValidateScriptArtifact(p, "scripts/trackfw-validate.sh", cfg)
	if execBitRepresentavelPara(t, p) {
		if finding == nil {
			t.Fatal("expected scaffold-wrong-mode finding for 0644 script, got nil")
		}
		if finding.FindingKind != integrations.DoctorScaffoldWrongMode {
			t.Errorf("expected scaffold-wrong-mode, got %q", finding.FindingKind)
		}
	} else {
		execBitNaoExercitado(t, p)
	}
}

// TestWrongModeDetection_StaticScript verifies AC2/AC3 for a static script.
func TestWrongModeDetection_StaticScript(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	relPath := "scripts/trackfw-attention-signal.sh"
	p := filepath.Join(dir, relPath)
	// Write correct content but wrong mode.
	if err := os.WriteFile(p, []byte(attentionSignalScript), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(attentionSignalScript), true, true)
	if execBitRepresentavelPara(t, p) {
		if finding == nil {
			t.Fatal("expected scaffold-wrong-mode finding, got nil")
		}
		if finding.FindingKind != integrations.DoctorScaffoldWrongMode {
			t.Errorf("expected scaffold-wrong-mode, got %q", finding.FindingKind)
		}
	} else {
		execBitNaoExercitado(t, p)
	}
}

// TestWrongModeDetection_ContentDivergence_TakesPrecedence verifies that a file
// with both wrong content and wrong mode produces scaffold-divergent, not
// scaffold-wrong-mode (content divergence takes precedence — AC3).
func TestWrongModeDetection_ContentDivergence_TakesPrecedence(t *testing.T) {
	// No platform guard here, on purpose: checkScaffoldArtifact checks
	// content BEFORE the execute bit (bytes.Equal at scaffold_doctor.go
	// precedes the CurrentGOOS/execBitPresent branch), so this assertion
	// never touches the execute bit and holds unconditionally on every
	// platform. A t.Skip("execute bit not applicable...") here was
	// leftover copy-paste from the neighboring mode tests, not a real
	// platform dependency — see the ML-1A scan report.
	dir := t.TempDir()
	relPath := "scripts/trackfw-attention-signal.sh"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	// Wrong content AND wrong mode.
	if err := os.WriteFile(p, []byte("wrong content\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(attentionSignalScript), true, true)
	if finding == nil {
		t.Fatal("expected a finding, got nil")
	}
	if finding.FindingKind != integrations.DoctorScaffoldDivergent {
		t.Errorf("expected scaffold-divergent (content takes precedence), got %q", finding.FindingKind)
	}
}

// TestExecBitFalse_NotAccusedForMissingBit verifies AC4/AC11: an artifact with
// execBit=false is never accused of a missing execute bit, even when at 0644.
func TestExecBitFalse_NotAccusedForMissingBit(t *testing.T) {
	dir := t.TempDir()
	relPath := ".claude/commands/trackfw/example.md"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	content := "# example slash command\n"
	// Write with 0644 (no execute bit) — correct for this artifact type.
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(content), true, false)
	if finding != nil {
		t.Errorf("expected no finding for 0644 non-executable artifact, got: %+v", finding)
	}
}

// TestExecBitPresent_UmaskNarrowedMode_Accepted verifies AC10: a file with mode 0700
// (umask 077 on 0755) has the owner-execute bit set and must NOT be accused.
func TestExecBitPresent_UmaskNarrowedMode_Accepted(t *testing.T) {
	dir := t.TempDir()
	relPath := "scripts/trackfw-credential-guard.sh"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(credentialGuardScript), 0o755); err != nil {
		t.Fatal(err)
	}
	// Narrow the mode to 0700 — simulates umask 077.
	if err := os.Chmod(p, 0o700); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(credentialGuardScript), true, true)
	if execBitRepresentavelPara(t, p) {
		if finding != nil {
			t.Errorf("expected no finding for 0700 (execute bit present), got: %+v", finding)
		}
	} else {
		execBitNaoExercitado(t, p)
	}
}

// TestWindowsPlatformGuard verifies AC5: on "windows", mode check is suppressed
// even if the file has 0644 and correct content → no scaffold-wrong-mode finding.
func TestWindowsPlatformGuard(t *testing.T) {
	// Override CurrentGOOS to simulate Windows.
	prev := CurrentGOOS
	CurrentGOOS = "windows"
	defer func() { CurrentGOOS = prev }()

	dir := t.TempDir()
	relPath := "scripts/trackfw-attention-signal.sh"
	p := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	// Correct content, wrong mode — on Windows this must be silent.
	if err := os.WriteFile(p, []byte(attentionSignalScript), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkScaffoldArtifact(p, relPath, []byte(attentionSignalScript), true, true)
	if finding != nil {
		t.Errorf("expected no finding on Windows (mode check suppressed), got: %+v", finding)
	}
}

// TestWindowsPlatformGuard_ValidateScript verifies AC5 for checkValidateScriptArtifact.
func TestWindowsPlatformGuard_ValidateScript(t *testing.T) {
	prev := CurrentGOOS
	CurrentGOOS = "windows"
	defer func() { CurrentGOOS = prev }()

	cfg := Config{}
	goNodeForm := buildValidateScript(cfg)

	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "scripts/trackfw-validate.sh")
	if err := os.WriteFile(p, []byte(goNodeForm), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, 0o644); err != nil {
		t.Fatal(err)
	}

	finding := checkValidateScriptArtifact(p, "scripts/trackfw-validate.sh", cfg)
	if finding != nil {
		t.Errorf("expected no finding on Windows (mode check suppressed), got: %+v", finding)
	}
}

// ---------------------------------------------------------------------------
// Tests for IsProducerGoMod and BuildDiscoverGitHubActionsWorkflowContent
// (REQ-2026-09-17, AC1/AC2/AC3/AC6).
// ---------------------------------------------------------------------------

// TestIsProducerGoMod verifies that the go.mod signal correctly identifies the
// producer repo and a consumer project. Affirms ML-1A AC1: the discriminant is
// the go.mod declaration, not a hard-coded path or an exception list.
func TestIsProducerGoMod(t *testing.T) {
	cases := []struct {
		name    string
		content string // go.mod content; "" means no go.mod
		want    bool
	}{
		{
			name:    "trackfw producer module",
			content: "module github.com/kgsaran/trackfw\n\ngo 1.25.2\n",
			want:    true,
		},
		{
			name:    "consumer module",
			content: "module example.com/myapp\n\ngo 1.22\n",
			want:    false,
		},
		{
			name:    "module that requires trackfw but is not the producer",
			content: "module example.com/myapp\n\ngo 1.22\n\nrequire (\n\tgithub.com/kgsaran/trackfw v8.0.0\n)\n",
			want:    false,
		},
		{
			name:    "missing go.mod",
			content: "",
			want:    false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			if tc.content != "" {
				if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(tc.content), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			got := IsProducerGoMod(dir)
			if got != tc.want {
				t.Errorf("IsProducerGoMod = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestBuildDiscoverGitHubActionsWorkflowContent_Templates verifies that the producer
// template compiles from source and the consumer template installs from release,
// including the counter-arm required by AC6: before the fix both contexts returned the
// same consumer template (go install unconditionally), so the two templates must differ
// and each must contain exactly the expected install mechanism.
//
// Affirms ML-1A AC1 (producer compiles from source), AC3/AC4 (consumer uses updated
// actions and go-version), and AC6 counter-arm (templates differ — fix has effect).
func TestBuildDiscoverGitHubActionsWorkflowContent_Templates(t *testing.T) {
	producer := BuildDiscoverGitHubActionsWorkflowContent(true)
	consumer := BuildDiscoverGitHubActionsWorkflowContent(false)

	// AC1: producer must compile from source. Use "- run: go install" to check the
	// run step precisely — the YAML comment in the producer template mentions "go install"
	// in the warning text but must not appear as an executable step.
	if strings.Contains(producer, "- run: go install") {
		t.Error("producer template must not have a 'run: go install' step — must compile from source")
	}
	if !strings.Contains(producer, "- run: go build") {
		t.Error("producer template must contain a 'run: go build' step")
	}
	if !strings.Contains(producer, "go-version-file: go.mod") {
		t.Error("producer template must use go-version-file: go.mod (AC3)")
	}

	// AC1: consumer must install from release.
	if strings.Contains(consumer, "- run: go build") {
		t.Error("consumer template must not have a 'run: go build' step")
	}
	if !strings.Contains(consumer, "- run: go install") {
		t.Error("consumer template must contain a 'run: go install' step")
	}
	if !strings.Contains(consumer, "@v") {
		t.Error("consumer template must pin the version with @v<version> (AC8)")
	}

	// AC3/AC4: both templates must use @v7 for actions.
	for _, tmpl := range []struct {
		name    string
		content string
	}{{"producer", producer}, {"consumer", consumer}} {
		if !strings.Contains(tmpl.content, "actions/checkout@v7") {
			t.Errorf("%s template: expected actions/checkout@v7 (AC4 regression guard)", tmpl.name)
		}
		if !strings.Contains(tmpl.content, "actions/setup-go@v7") {
			t.Errorf("%s template: expected actions/setup-go@v7 (AC4 regression guard)", tmpl.name)
		}
	}

	// AC6 counter-arm: the two templates must differ — if they were the same (as before
	// the fix, when both returned the consumer template with go install), the go.mod
	// signal has no effect. Both had "- run: go install" before the fix.
	if producer == consumer {
		t.Error("counter-arm failed: producer and consumer templates are identical — the go.mod discriminant has no effect (simulates pre-fix state where both returned go install)")
	}
	// The pre-fix (counter-arm): both templates previously had "- run: go install".
	// After the fix: only the consumer has it.
	if !strings.Contains(consumer, "- run: go install") {
		t.Error("counter-arm: consumer template must have '- run: go install' (as both did before the fix)")
	}
	if strings.Contains(producer, "- run: go install") {
		t.Error("counter-arm: producer template must not have '- run: go install' (this is the fix)")
	}
}

// TestRunScaffoldDoctor_DiscoverWorkflow_ProducerContext_Clean proves AC2 for the
// doctor call site (scaffold_doctor.go:269): when the go.mod declares this module,
// RunScaffoldDoctor compares against the producer template — a file matching that
// template is reported clean and does not trigger the false-positive that caused #376.
//
// Affirms ML-1A AC2: the doctor call site passes the correct context and the previously
// broken comparison (producer repo always reported scaffold-divergent) is resolved.
func TestRunScaffoldDoctor_DiscoverWorkflow_ProducerContext_Clean(t *testing.T) {
	dir := t.TempDir()
	mustWriteGoMod(t, dir, "github.com/kgsaran/trackfw")
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("backend: go\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Write the producer template as the current disk content.
	producerContent := BuildDiscoverGitHubActionsWorkflowContent(true)
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-validate.yml"), []byte(producerContent), 0o644); err != nil {
		t.Fatal(err)
	}

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	for _, f := range findings {
		if f.Destination == DiscoverGitHubActionsWorkflowPath {
			t.Errorf("expected no finding for producer fixture with producer template, got: %+v", f)
		}
	}
}

// TestRunScaffoldDoctor_DiscoverWorkflow_WrongContext_Divergent proves AC2: when the
// disk content uses the wrong template for the context (consumer template in a producer
// repo), the doctor reports scaffold-divergent — the false positive of the old code
// becomes the correct positive of the fixed code for the opposite mismatch.
//
// Affirms ML-1A AC2: all three call sites must agree on the context; a mismatch between
// what the builder emits and what lives on disk is correctly detected in both directions.
func TestRunScaffoldDoctor_DiscoverWorkflow_WrongContext_Divergent(t *testing.T) {
	dir := t.TempDir()
	mustWriteGoMod(t, dir, "github.com/kgsaran/trackfw")
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("backend: go\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Write the CONSUMER template in a producer fixture — this is the pre-fix scenario.
	consumerContent := BuildDiscoverGitHubActionsWorkflowContent(false)
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-validate.yml"), []byte(consumerContent), 0o644); err != nil {
		t.Fatal(err)
	}

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	found := false
	for _, f := range findings {
		if f.Destination == DiscoverGitHubActionsWorkflowPath {
			found = true
			if f.FindingKind != integrations.DoctorScaffoldDivergent {
				t.Errorf("expected DoctorScaffoldDivergent, got %v", f.FindingKind)
			}
		}
	}
	if !found {
		t.Errorf("expected scaffold-divergent for consumer template in producer fixture, got none: %+v", findings)
	}
}

// mustWriteGoMod is a test helper that writes a minimal go.mod with the given module
// path to the given directory.
func mustWriteGoMod(t *testing.T, dir, modulePath string) {
	t.Helper()
	content := "module " + modulePath + "\n\ngo 1.25.2\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// ─── ML-1A (ADR-2026-09-29 D4): doctor suppresses scaffold-missing for gate.yml ──

// TestRunScaffoldDoctor_GateYmlMissing_ValidateYmlPresent_Silent asserts that when
// trackfw-validate.yml is present and trackfw-gate.yml is absent (with ci: github-actions),
// the doctor emits NO finding for gate.yml — the scaffold-missing finding is suppressed.
//
// ML-1A Regra Dura de Reconciliação sentence: this test affirms that ADR-2026-09-29 D4 is
// implemented — skipping the gate.yml write (D2) does not trade a duplication for a false
// scaffold-missing finding; the doctor is aware that validate.yml's presence makes gate.yml
// absence expected.
func TestRunScaffoldDoctor_GateYmlMissing_ValidateYmlPresent_Silent(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("ci: github-actions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Only validate.yml present — gate.yml intentionally absent.
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-validate.yml"), []byte(BuildDiscoverGitHubActionsWorkflowContent(false)), 0o644); err != nil {
		t.Fatal(err)
	}

	// Reset the config singleton so loadUpdateConfig() reads from dir's trackfw.yaml
	// (not from a prior test's cached result — config.Load() is a singleton).
	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	for _, f := range findings {
		if f.Destination == GitHubActionsWorkflowPath {
			t.Errorf("unexpected finding for gate.yml when validate.yml is present: %+v", f)
		}
	}
}

// TestRunScaffoldDoctor_BothMissing_GitHubActions_Accuses is the counter-arm: when BOTH
// workflows are absent (and ci: github-actions), the doctor MUST still accuse scaffold-missing
// for gate.yml — the true finding must not have been erased.
//
// ML-1A Regra Dura de Reconciliação sentence: this test affirms that D4's suppression is
// conditional on validate.yml's presence — when neither workflow exists, the missing-gate
// finding is not suppressed, preserving the doctor's original behaviour for new projects
// that ran init but somehow lost the workflow.
func TestRunScaffoldDoctor_BothMissing_GitHubActions_Accuses(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("ci: github-actions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// Neither gate.yml nor validate.yml present.

	// Reset the config singleton so loadUpdateConfig() reads from dir's trackfw.yaml.
	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	found := false
	for _, f := range findings {
		if f.Destination == GitHubActionsWorkflowPath {
			found = true
			if f.FindingKind != integrations.DoctorScaffoldMissing {
				t.Errorf("expected DoctorScaffoldMissing for gate.yml when both absent, got %v", f.FindingKind)
			}
		}
	}
	if !found {
		t.Errorf("counter-arm: expected scaffold-missing for gate.yml when both workflows absent; got none: %+v", findings)
	}
}

// TestRunScaffoldDoctor_GateYmlStale_ValidateYmlPresent_Accuses is the counter-arm for
// stale gate.yml: even when validate.yml is present, a STALE gate.yml must still be
// accused (scaffold-divergent). Suppression is ONLY for scaffold-missing.
//
// ML-1A Regra Dura de Reconciliação sentence: this test affirms that D4's suppression
// does not swallow scaffold-divergent findings — a gate.yml that exists but is outdated
// remains a finding regardless of whether validate.yml is also present.
func TestRunScaffoldDoctor_GateYmlStale_ValidateYmlPresent_Accuses(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("ci: github-actions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// validate.yml present (correct content).
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-validate.yml"), []byte(BuildDiscoverGitHubActionsWorkflowContent(false)), 0o644); err != nil {
		t.Fatal(err)
	}
	// gate.yml present but obviously stale — content does not match any template.
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-gate.yml"), []byte("stale: true\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Reset the config singleton so loadUpdateConfig() reads from dir's trackfw.yaml.
	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	found := false
	for _, f := range findings {
		if f.Destination == GitHubActionsWorkflowPath {
			found = true
			if f.FindingKind != integrations.DoctorScaffoldDivergent {
				t.Errorf("expected DoctorScaffoldDivergent for stale gate.yml, got %v", f.FindingKind)
			}
		}
	}
	if !found {
		t.Errorf("counter-arm: expected scaffold-divergent for stale gate.yml even when validate.yml present; got none: %+v", findings)
	}
}

// ─── ML-1B (ADR-2026-09-29 D3): doctor names the duplication when both are present ──

// TestRunScaffoldDoctor_BothPresent_EmitsMigration asserts that when both
// trackfw-gate.yml and trackfw-validate.yml are present as regular files (and ci:
// github-actions), the doctor emits a scaffold-workflow-duplicated finding, naming both
// workflows, both job ids, and the required_status_checks check.
//
// ML-1B Regra Dura de Reconciliação sentence: this test affirms that ADR-2026-09-29 D3
// is implemented — a project that already has both workflows receives a migration advisory
// from the doctor, so the consumer knows the duplication exists and what to verify before
// removing the redundant workflow.
func TestRunScaffoldDoctor_BothPresent_EmitsMigration(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("ci: github-actions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Both workflows present as regular files with correct content.
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-gate.yml"), []byte(buildGitHubActionsWorkflowContent(false)), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-validate.yml"), []byte(BuildDiscoverGitHubActionsWorkflowContent(false)), 0o644); err != nil {
		t.Fatal(err)
	}

	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	var migration *integrations.DoctorFinding
	for i := range findings {
		if findings[i].FindingKind == integrations.DoctorScaffoldWorkflowDuplicated {
			migration = &findings[i]
			break
		}
	}
	if migration == nil {
		t.Fatalf("expected scaffold-workflow-duplicated finding when both workflows present; got none: %+v", findings)
	}
	// The finding must name both files and both job ids in the remedy.
	for _, want := range []string{
		GitHubActionsWorkflowPath,
		DiscoverGitHubActionsWorkflowPath,
		"governance-install-script",
		"governance-go-install",
		"required_status_checks",
	} {
		if !strings.Contains(migration.Remedy, want) {
			t.Errorf("migration finding remedy missing %q; remedy: %s", want, migration.Remedy)
		}
	}
	// The finding must not suggest unconditional removal — it is advisory.
	if migration.FindingKind != integrations.DoctorScaffoldWorkflowDuplicated {
		t.Errorf("expected DoctorScaffoldWorkflowDuplicated, got %v", migration.FindingKind)
	}
}

// ─── ML-1D (ADR-2026-09-29): doctor skips validate.yml when it is a symlink ──

// TestRunScaffoldDoctor_DiscoverWorkflow_Symlink_Silent asserts that when
// trackfw-validate.yml is a symlink (even pointing at stale content), the doctor emits
// NO scaffold-divergent finding for it — the symlink case is silently skipped because
// trackfw update refuses to write through symlinks, making scaffold-divergent's remedy
// inoperable.
//
// The symlink target contains stale content (no match to any known template) so that
// the pre-fix os.Stat path would have emitted scaffold-divergent; with os.Lstat + the
// symlink exclusion the finding disappears. This makes the test a genuine falsifier.
//
// ML-1D Regra Dura de Reconciliação sentence: this test affirms that ML-1D's Lstat
// change is effective — a symlink at validate.yml no longer generates a scaffold-divergent
// finding with an inoperable remedy (trackfw update), consistent with the pattern used
// by discoverWorkflowPresent and the D3 gatePresent check.
func TestRunScaffoldDoctor_DiscoverWorkflow_Symlink_Silent(t *testing.T) {
	dir := t.TempDir()
	// trackfw.yaml required for RunScaffoldDoctor eligibility check.
	// No ci: key so the gate.yml CI section does not run — only the discover section.
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("backend: go\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Create a target with stale content — pre-fix os.Stat would follow the link,
	// compare "stale: true\n" to the template, and emit scaffold-divergent.
	outside := t.TempDir()
	staleTarget := filepath.Join(outside, "stale-workflow.yml")
	if err := os.WriteFile(staleTarget, []byte("stale: true\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	validatePath := filepath.Join(wfDir, "trackfw-validate.yml")
	symlinkOrSkip(t, staleTarget, validatePath)

	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	for _, f := range findings {
		if f.Destination == DiscoverGitHubActionsWorkflowPath {
			t.Errorf("unexpected finding for symlinked validate.yml — remedy would be inoperable: %+v", f)
		}
	}
}

// TestRunScaffoldDoctor_DiscoverWorkflow_RegularStale_Accuses is the counter-arm:
// when validate.yml is a REGULAR FILE with stale content, the doctor must still emit
// scaffold-divergent — the Lstat guard must not suppress real divergence.
//
// ML-1D Regra Dura de Reconciliação sentence: this test affirms that the Lstat change
// is scoped to symlinks only — a regular file with wrong content is still accused,
// preserving the doctor's ability to detect genuine drift in the validate.yml template.
func TestRunScaffoldDoctor_DiscoverWorkflow_RegularStale_Accuses(t *testing.T) {
	dir := t.TempDir()
	// trackfw.yaml required for RunScaffoldDoctor eligibility check.
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("backend: go\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Regular file with stale content — must still be accused.
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-validate.yml"), []byte("stale: true\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	found := false
	for _, f := range findings {
		if f.Destination == DiscoverGitHubActionsWorkflowPath {
			found = true
			if f.FindingKind != integrations.DoctorScaffoldDivergent {
				t.Errorf("expected DoctorScaffoldDivergent for stale regular validate.yml, got %v", f.FindingKind)
			}
		}
	}
	if !found {
		t.Errorf("counter-arm: expected scaffold-divergent for stale regular validate.yml; got none: %+v", findings)
	}
}

// TestRunScaffoldDoctor_OnlyGateYml_NoMigration is the counter-arm: when only gate.yml
// is present (validate.yml absent), no migration finding must be emitted.
//
// ML-1B Regra Dura de Reconciliação sentence: this test affirms that D3 fires only when
// BOTH workflows are present — a project with only gate.yml (the normal post-migration
// state) receives no advisory, preserving doctor's silence in the healthy single-workflow
// case.
func TestRunScaffoldDoctor_OnlyGateYml_NoMigration(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "trackfw.yaml"), []byte("ci: github-actions\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	wfDir := filepath.Join(dir, ".github", "workflows")
	if err := os.MkdirAll(wfDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Only gate.yml present — validate.yml intentionally absent.
	if err := os.WriteFile(filepath.Join(wfDir, "trackfw-gate.yml"), []byte(buildGitHubActionsWorkflowContent(false)), 0o644); err != nil {
		t.Fatal(err)
	}

	config.Reset()
	t.Cleanup(config.Reset)

	findings, err := RunScaffoldDoctor(dir)
	if err != nil {
		t.Fatalf("RunScaffoldDoctor error: %v", err)
	}
	for _, f := range findings {
		if f.FindingKind == integrations.DoctorScaffoldWorkflowDuplicated {
			t.Errorf("unexpected scaffold-workflow-duplicated finding when only gate.yml present: %+v", f)
		}
	}
}
