#!/usr/bin/env bash
# check-attention-scripts-parity.sh — proves the PROJECT-scope hook scripts
# emitted by `trackfw discover --init` (trackfw-attention-signal.sh,
# trackfw-attention-cleanup.sh and, since ML-0B of
# ROADMAP-2026-08-12-deteccao-de-adulteracao-do-credential-guard-regra-de-validate,
# trackfw-credential-guard.sh and, since ML-4B of
# ROADMAP-2026-08-16-higiene-sete-debitos-acumulados-da-entrega-de-plugins-e-da-release-7-0-0,
# trackfw-git-branch-guard.sh) are byte-identical across Go, Node.js and
# Python. The three runtimes each embed the script content as a source
# literal (internal/generators/scaffold.go, npm/src/generators/hooks.js,
# pypi/trackfw/generators/init_gen.py) — nothing enforced this stayed in sync
# until now, and the two attention literals drifted (comment language, a
# blank line, `sed` invocation style) without any gate noticing
# (see docs/req/REQ-2026-08-04-scripts-de-attention-hooks-divergem-em-conteudo-entre-go-node-e-python-sem-gate-de-paridade.md).
#
# trackfw-credential-guard.sh (ML-0B, 2026-08-12): a Go-only unit test already
# existed — TestCredentialGuardScript_ParityAcrossStacks
# (internal/generators/credential_guard_test.go) — but it regex-scrapes the
# CG_* / _CG_* block literals out of hooks.js/init_gen.py SOURCE TEXT and
# reconstructs the script by concatenating them in a Go-hardcoded order; it
# never executes Node or Python, so it cannot see a bug in the runtime's OWN
# composition line (`CREDENTIAL_GUARD_SCRIPT = CG_HEADER + ...`). Verified
# concretely: swapping the order of that one Node.js concatenation line makes
# `discover --init` emit a script where the project-root no-op guard moves
# past the detection core (a real behavioral break — the guard would run
# unconditionally instead of gating everything after it), while
# `go test -run ParityAcrossStacks` stays green throughout, because it never
# reads the CREDENTIAL_GUARD_SCRIPT constant, only the four block literals in
# isolation. This gate closes that gap by running `discover --init` for real
# in all three runtimes (same entry point already used for the two attention
# scripts) and diffing the actual emitted file — the same end-to-end guarantee
# `check-attention-scripts-parity.sh` already gave the other two scripts.
#
# Scope decision — PROJECT variant only, not global: the new `validate` rule
# this gate is a prerequisite for (Wave 1 of the roadmap above) anchors on the
# project-scope script (scripts/trackfw-credential-guard.sh), generated here
# via `discover --init` exactly like the two attention scripts. The global
# variant (~/.trackfw/scripts/trackfw-credential-guard.sh, written by
# `trackfw update harness`) is NOT covered end-to-end here — extending this
# gate to it would require driving `update harness` with a fixture $HOME in
# all three runtimes, which is unverified/out of scope for what the anchor
# actually needs. The existing Go-only TestGlobalCredentialGuardScript_
# ParityAcrossStacks keeps its (weaker, non-executing) coverage for that
# variant; if the global script becomes a validate anchor too, extend this
# gate the same way then — do not presume it is covered now. Same scope
# restriction applies to trackfw-git-branch-guard.sh (added by ML-4B of
# ROADMAP-2026-08-16-higiene-sete-debitos-acumulados-da-entrega-de-plugins-e-
# da-release-7-0-0): only the PROJECT-scope copy (scripts/trackfw-git-branch-
# guard.sh, generated by `discover --init`) is covered here — the global copy
# (~/.trackfw/scripts/trackfw-git-branch-guard.sh, written by `trackfw update
# harness`) is NOT.
#
# Follows the conventions of scripts/check-branch-new-parity.sh: set -euo pipefail,
# mktemp -d fixture with a cleanup trap, BASH_SOURCE-relative ROOT_DIR, GO_BIN
# resolution (build a throwaway binary if unset), byte-level diff -u between
# runtimes (never a hash-only comparison — a hash mismatch alone gives no
# actionable diagnostic).
set -euo pipefail

# Codificacao de saida (ML-1B, ROADMAP-2026-09-02-saida-nao-ascii-declara-
# codificacao-em-script-gerado-e-em-gate): forca UTF-8 no stdio de todo
# python3 deste gate. Sob console cp1252 (Windows) o Python herda a codepage
# e um print() de caractere fora do cp1252 estoura UnicodeEncodeError -- o
# gate reprova por um motivo alheio ao que ele mede. Declarado aqui, e nao no
# Makefile, para valer tambem na invocacao direta pelo workflow de CI, na
# invocacao manual de um gate isolado e na invocacao de um gate por outro.
# Trade-off assumido: num console genuinamente cp1252 a saida vira mojibake
# em vez de crashar -- acento ilegivel com exit code correto vale mais que
# uma reprovacao falsa.
export PYTHONIOENCODING=utf-8

export NO_COLOR=1
export TERM=dumb

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
WORK=$(mktemp -d "${TMPDIR:-/tmp}/trackfw-attention-scripts-parity.XXXXXX")
trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------------------
# Resolve the three runtimes — mirrors check-branch-new-parity.sh:
#   GO_BIN unset → build a throwaway binary so the script also works standalone.
#   GO_BIN relative → prefix with ROOT_DIR.
# ---------------------------------------------------------------------------
if [[ -z "${GO_BIN:-}" ]]; then
  GO_BIN="$WORK/trackfw-go"
  (cd "$ROOT_DIR" && GOCACHE="$WORK/go-build-cache" go build -o "$GO_BIN" ./cmd/trackfw)
elif [[ "$GO_BIN" != /* ]]; then
  GO_BIN="$ROOT_DIR/$GO_BIN"
fi
NODE_CLI="$ROOT_DIR/npm/bin/trackfw"
PY_ROOT="${PY_ROOT:-$ROOT_DIR/pypi}"

if [[ ! -x "$GO_BIN" ]]; then
  echo "check-attention-scripts-parity: Go binary not found/executable at $GO_BIN" >&2
  exit 1
fi
if [[ ! -f "$NODE_CLI" ]]; then
  echo "check-attention-scripts-parity: Node CLI not found at $NODE_CLI" >&2
  exit 1
fi

FAIL=0
ok()   { echo "OK   [$1]"; }
fail() { echo "FAIL [$1]: $2" >&2; FAIL=1; }

# ---------------------------------------------------------------------------
# Generate the two scripts with each runtime via `discover --init` on a fresh,
# empty fixture directory (the same entry point used in production — no
# reliance on internal generator APIs, so the gate also catches a runtime that
# stops wiring the generator into `discover --init`).
# ---------------------------------------------------------------------------
run_discover_init() {
  local runtime=$1 dir=$2
  mkdir -p "$dir"
  case "$runtime" in
    go)   (cd "$dir" && "$GO_BIN" discover --init)                              >/dev/null 2>"$WORK/$runtime.err" ;;
    node) (cd "$dir" && node "$NODE_CLI" discover --init)                       >/dev/null 2>"$WORK/$runtime.err" ;;
    py)   (cd "$dir" && PYTHONPATH="$PY_ROOT" python3 -m trackfw discover --init) >/dev/null 2>"$WORK/$runtime.err" ;;
    *)    echo "run_discover_init: unknown runtime '$runtime'" >&2; exit 1 ;;
  esac
}

GO_DIR="$WORK/go"
NODE_DIR="$WORK/node"
PY_DIR="$WORK/py"

set +e
run_discover_init go "$GO_DIR"
GO_STATUS=$?
run_discover_init node "$NODE_DIR"
NODE_STATUS=$?
run_discover_init py "$PY_DIR"
PY_STATUS=$?
set -e

for pair in "go:$GO_STATUS" "node:$NODE_STATUS" "py:$PY_STATUS"; do
  runtime=${pair%%:*}
  status=${pair##*:}
  if [[ "$status" -ne 0 ]]; then
    fail "attention-scripts-parity/$runtime/discover-init" \
      "discover --init exited $status; stderr: $(cat "$WORK/$runtime.err" 2>/dev/null)"
  fi
done

# ---------------------------------------------------------------------------
# P2 vacuity guard: if any runtime failed to even produce the two files, a
# byte-for-byte diff of empty/missing files would trivially "pass" — assert
# both scripts exist and are non-empty for all three runtimes before diffing.
# ---------------------------------------------------------------------------
for runtime_dir in "go:$GO_DIR" "node:$NODE_DIR" "py:$PY_DIR"; do
  runtime=${runtime_dir%%:*}
  dir=${runtime_dir##*:}
  for script in trackfw-attention-signal.sh trackfw-attention-cleanup.sh trackfw-credential-guard.sh trackfw-git-branch-guard.sh; do
    path="$dir/scripts/$script"
    if [[ ! -s "$path" ]]; then
      fail "attention-scripts-parity/$runtime/$script" "missing or empty: $path"
    fi
  done
done

if [[ "$FAIL" -ne 0 ]]; then
  echo
  echo "check-attention-scripts-parity.sh: one or more scenarios FAILED (setup)." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Byte-for-byte diff of both scripts, go-vs-node and go-vs-py.
# ---------------------------------------------------------------------------
for script in trackfw-attention-signal.sh trackfw-attention-cleanup.sh trackfw-credential-guard.sh trackfw-git-branch-guard.sh; do
  go_file="$GO_DIR/scripts/$script"
  node_file="$NODE_DIR/scripts/$script"
  py_file="$PY_DIR/scripts/$script"

  if diff -u "$go_file" "$node_file" >"$WORK/$script.diff.go-node" 2>&1; then
    ok "attention-scripts-parity/$script/go-vs-node"
  else
    fail "attention-scripts-parity/$script/go-vs-node" \
      "byte drift between Go and Node.js:
$(cat "$WORK/$script.diff.go-node")"
  fi

  if diff -u "$go_file" "$py_file" >"$WORK/$script.diff.go-py" 2>&1; then
    ok "attention-scripts-parity/$script/go-vs-py"
  else
    fail "attention-scripts-parity/$script/go-vs-py" \
      "byte drift between Go and Python:
$(cat "$WORK/$script.diff.go-py")"
  fi
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo
if [[ "$FAIL" -eq 0 ]]; then
  echo "All check-attention-scripts-parity.sh scenarios passed."
else
  echo "check-attention-scripts-parity.sh: one or more scenarios FAILED." >&2
fi
exit "$FAIL"
