'use strict'

// Tests for the validate.sh set-membership predicate in runScaffoldDoctor.
// Mirrors internal/generators/scaffold_doctor_test.go and
// pypi/tests/test_scaffold_doctor_membership.py.
//
// Durability anchor: if buildValidateScript or PYTHON_VALIDATE_SCRIPT_FORM changes,
// these tests break and force a conscious update of the membership set.

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const { checkValidateScriptArtifact, PYTHON_VALIDATE_SCRIPT_FORM, SCAFFOLD_DIVERGENT, SCAFFOLD_MISSING } =
  require('../src/integrations/scaffold_doctor')
const { buildValidateScript } = require('../src/generators/init')

const EMPTY_CFG = { backend: null, frontend: null, pkgManager: null, ci: null }

function withFile(content, fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'trackfw-validate-test-'))
  const scriptsDir = path.join(dir, 'scripts')
  fs.mkdirSync(scriptsDir)
  const absPath = path.join(scriptsDir, 'trackfw-validate.sh')
  fs.writeFileSync(absPath, content, 'utf8')
  fs.chmodSync(absPath, 0o755)
  return fn(absPath)
}

test('checkValidateScriptArtifact: Go/Node form accepted (no finding)', () => {
  const goNodeForm = buildValidateScript(EMPTY_CFG)
  withFile(goNodeForm, (absPath) => {
    const f = checkValidateScriptArtifact(absPath, 'scripts/trackfw-validate.sh', EMPTY_CFG)
    assert.equal(f, null, 'Go/Node form must be accepted without a finding')
  })
})

test('checkValidateScriptArtifact: Python form accepted (no finding)', () => {
  withFile(PYTHON_VALIDATE_SCRIPT_FORM, (absPath) => {
    const f = checkValidateScriptArtifact(absPath, 'scripts/trackfw-validate.sh', EMPTY_CFG)
    assert.equal(f, null, 'Python form must be accepted without a finding')
  })
})

test('checkValidateScriptArtifact: near-miss Go form (set -x) refused (scaffold-divergent)', () => {
  const nearMiss =
    '#!/usr/bin/env sh\n# trackfw governance gate — generated by trackfw init\nset -x\n\n' +
    'echo "→ trackfw: validating governance..."\ntrackfw validate\n\n\necho "✓ all checks passed."\n'
  withFile(nearMiss, (absPath) => {
    const f = checkValidateScriptArtifact(absPath, 'scripts/trackfw-validate.sh', EMPTY_CFG)
    assert.ok(f !== null, 'near-miss must be accused')
    assert.equal(f.finding, SCAFFOLD_DIVERGENT)
  })
})

test('checkValidateScriptArtifact: hand-edited content refused (scaffold-divergent)', () => {
  withFile('trackfw validate\n', (absPath) => {
    const f = checkValidateScriptArtifact(absPath, 'scripts/trackfw-validate.sh', EMPTY_CFG)
    assert.ok(f !== null, 'hand-edited content must be accused')
    assert.equal(f.finding, SCAFFOLD_DIVERGENT)
  })
})

test('checkValidateScriptArtifact: missing file produces scaffold-missing', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'trackfw-validate-test-'))
  const absPath = path.join(dir, 'scripts', 'trackfw-validate.sh')
  const f = checkValidateScriptArtifact(absPath, 'scripts/trackfw-validate.sh', EMPTY_CFG)
  assert.ok(f !== null, 'missing file must produce a finding')
  assert.equal(f.finding, SCAFFOLD_MISSING)
})
