"""
test_scaffold_doctor_membership.py — unit tests for the validate.sh set-membership
predicate in run_scaffold_doctor.

Mirrors internal/generators/scaffold_doctor_test.go and
npm/tests/scaffold_doctor_membership.test.js.

Durability anchor: if _build_go_node_validate_script or _VALIDATE_SCRIPT_CONTENT
changes, these tests break and force a conscious update of the membership set.
"""

import os
import tempfile
import unittest

from trackfw.generators.init_gen import _VALIDATE_SCRIPT_CONTENT
from trackfw.integrations.scaffold_doctor import (
    _build_go_node_validate_script,
    _check_validate_script_artifact,
)
from trackfw.integrations.doctor import SCAFFOLD_DIVERGENT, SCAFFOLD_MISSING

EMPTY_CFG: dict = {'backend': None, 'frontend': None, 'pkg_manager': None}


def _write_validate_file(tmpdir: str, content: str) -> str:
    scripts_dir = os.path.join(tmpdir, 'scripts')
    os.makedirs(scripts_dir, exist_ok=True)
    dest = os.path.join(scripts_dir, 'trackfw-validate.sh')
    with open(dest, 'w', encoding='utf-8') as f:
        f.write(content)
    os.chmod(dest, 0o755)
    return tmpdir


class TestValidateScriptMembership(unittest.TestCase):
    """_check_validate_script_artifact must accept both known forms and refuse near-misses."""

    def test_go_node_form_accepted(self):
        go_node_form = _build_go_node_validate_script(EMPTY_CFG)
        with tempfile.TemporaryDirectory() as tmpdir:
            _write_validate_file(tmpdir, go_node_form)
            finding = _check_validate_script_artifact(tmpdir, EMPTY_CFG)
        self.assertIsNone(finding, 'Go/Node form must be accepted without a finding')

    def test_python_form_accepted(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            _write_validate_file(tmpdir, _VALIDATE_SCRIPT_CONTENT)
            finding = _check_validate_script_artifact(tmpdir, EMPTY_CFG)
        self.assertIsNone(finding, 'Python form must be accepted without a finding')

    def test_near_miss_go_form_refused(self):
        """Go form with `set -x` instead of `set -e` must be accused."""
        near_miss = (
            '#!/usr/bin/env sh\n'
            '# trackfw governance gate — generated by trackfw init\n'
            'set -x\n\n'
            'echo "→ trackfw: validating governance..."\n'
            'trackfw validate\n\n\n'
            'echo "✓ all checks passed."\n'
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            _write_validate_file(tmpdir, near_miss)
            finding = _check_validate_script_artifact(tmpdir, EMPTY_CFG)
        self.assertIsNotNone(finding, 'near-miss must be accused')
        self.assertEqual(finding['finding'], SCAFFOLD_DIVERGENT)

    def test_hand_edited_content_refused(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            _write_validate_file(tmpdir, 'trackfw validate\n')
            finding = _check_validate_script_artifact(tmpdir, EMPTY_CFG)
        self.assertIsNotNone(finding, 'hand-edited content must be accused')
        self.assertEqual(finding['finding'], SCAFFOLD_DIVERGENT)

    def test_missing_file_produces_scaffold_missing(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            # Write trackfw.yaml but no validate.sh
            with open(os.path.join(tmpdir, 'trackfw.yaml'), 'w') as f:
                f.write('roadmap_dir: docs/roadmaps\n')
            finding = _check_validate_script_artifact(tmpdir, EMPTY_CFG)
        self.assertIsNotNone(finding, 'missing file must produce a finding')
        self.assertEqual(finding['finding'], SCAFFOLD_MISSING)


if __name__ == '__main__':
    unittest.main()
